#!/usr/bin/env python3
"""Run Disassemble Entry Points without pre-disassembling the executable section."""

from __future__ import annotations

import shutil
import sys
import tempfile
from pathlib import Path


ANALYZER = "Disassemble Entry Points"
DEPENDENCIES: tuple[str, ...] = ()
TARGETS = ("entry_point_alpha", "entry_point_beta", "entry_point_gamma", "entry_point_delta", "data_only_marker")


def configure_analysis(project, program) -> list[str]:
    """Disable unrelated booleans and explicitly enable the entry-point analyzer."""
    from ghidra.framework.options import OptionType

    options = project.getAnalysisOptions(program)
    enabled_names = {ANALYZER, *DEPENDENCIES}
    for name in options.getOptionNames():
        if options.getType(name) == OptionType.BOOLEAN_TYPE:
            options.setBoolean(name, str(name) in enabled_names)
    return sorted(str(name) for name in options.getOptionNames()
                  if options.getType(name) == OptionType.BOOLEAN_TYPE and options.getBoolean(name, False))


def target_symbols(program):
    """Find C and C++-linkage target symbols without assuming decorated names."""
    symbols = []
    iterator = program.getSymbolTable().getAllSymbols(True)
    while iterator.hasNext():
        symbol = iterator.next()
        if symbol.isExternal():
            continue
        raw_name = str(symbol.getName())
        display_name = str(symbol.getName(False))
        for target in TARGETS:
            if raw_name == target or display_name == target or raw_name.startswith(f"?{target}@@"):
                symbols.append((target, symbol, "C" if raw_name == target else "C++ decorated"))
                break
    return sorted(symbols, key=lambda row: (row[0], int(row[1].getAddress().getOffset())))


def target_facts(program):
    """Extract before/after-relevant state for C and C++ target symbols."""
    rows = []
    for target, symbol, linkage in target_symbols(program):
        address = symbol.getAddress()
        rows.append((target, linkage, f"0x{int(address.getOffset()):016X}",
                     program.getListing().getInstructionAt(address) is not None,
                     program.getFunctionManager().getFunctionAt(address) is not None))
    return sorted(rows)


def fact_delta(before, after):
    """Compare entry-point state by target and address and classify state changes."""
    key = lambda row: (row[0], row[2])
    before_by_key = {key(row): row for row in before}
    after_by_key = {key(row): row for row in after}
    added = [after_by_key[item] for item in sorted(set(after_by_key) - set(before_by_key))]
    removed = [before_by_key[item] for item in sorted(set(before_by_key) - set(after_by_key))]
    changed = [(before_by_key[item], after_by_key[item])
               for item in sorted(set(before_by_key) & set(after_by_key))
               if before_by_key[item] != after_by_key[item]]
    return added, removed, changed


def row_text(row) -> str:
    """Render one entry-point state row for a delta list."""
    name, linkage, address, instruction, function = row
    return f"`{name}` `{linkage}` `{address}` instruction `{str(instruction).lower()}` function `{str(function).lower()}`"


def delta_lines(before, after) -> list[str]:
    """Render explicit entry-point additions, removals, and state changes."""
    added, removed, changed = fact_delta(before, after)
    if not added and not removed and not changed:
        return ["## Delta", "", "No changes observed", ""]
    lines = ["## Delta", "", "### Added rows", ""]
    if added:
        lines.extend(f"- {row_text(row)}" for row in added)
    else:
        lines.append("- None")
    lines.extend(["", "### Removed rows", ""])
    if removed:
        lines.extend(f"- {row_text(row)}" for row in removed)
    else:
        lines.append("- None")
    lines.extend(["", "### Changed rows", ""])
    if changed:
        lines.extend(f"- {row_text(old)} -> {row_text(new)}" for old, new in changed)
    else:
        lines.append("- None")
    lines.append("")
    return lines


def entry_table(lines: list[str], phase: str, rows) -> None:
    """Append one phase table containing target instruction/function state."""
    lines.extend([f"## {phase}", "", "| Symbol | Linkage | Address | Instruction | Function |", "| --- | --- | --- | --- | --- |"])
    lines.extend(f"| `{name}` | `{linkage}` | `{address}` | `{str(instruction).lower()}` | `{str(function).lower()}` |"
                 for name, linkage, address, instruction, function in rows)


def report(input_path: Path, enabled: list[str], before, after) -> str:
    """Render phase entry-symbol state and an explicit analyzer delta."""
    lines = ["# Disassemble Entry Points Behavioral Fixture", "",
             "> Generated by PyGhidra without pre-disassembling executable bytes.", "", "## Analysis Configuration", "",
             f"- **Input:** `{input_path.name}`", f"- **Enabled boolean analyzers:** `{', '.join(enabled)}`", "",
             ""]
    entry_table(lines, "Before target analysis", before)
    lines.append("")
    entry_table(lines, "After target analysis", after)
    data_rows = [row for row in after if row[0] == "data_only_marker"]
    if not data_rows or any(row[3] or row[4] for row in data_rows):
        raise RuntimeError(f"C++ data negative control was not preserved: before={before}, after={after}")
    lines.extend(["", "## Fixture Assertions", "", f"- **Selected PE symbols before target analysis:** `{len(before)}`", f"- **Selected PE symbols after target analysis:** `{len(after)}`", "- The `data_only_marker` C++-linkage symbol remains non-instructional and functionless in both snapshots.", ""])
    lines.extend(delta_lines(before, after))
    return "\n".join(lines)


def main() -> int:
    """Create, save, reopen, analyze, save, and close an isolated Ghidra project."""
    fixture_dir = Path(__file__).resolve().parent
    input_path = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else fixture_dir / "test_disassemble_entry_points.exe"
    output_path = Path(sys.argv[2]).resolve() if len(sys.argv) > 2 else fixture_dir / "test_disassemble_entry_points.md"
    if not input_path.is_file():
        print(f"Input file does not exist: {input_path}", file=sys.stderr)
        return 2
    import pyghidra

    pyghidra.start()
    from ghidra.base.project import GhidraProject
    from java.io import File

    project_parent = Path(tempfile.mkdtemp(prefix="ghidra_disassemble_entry_points_"))
    project = None
    try:
        project = GhidraProject.createProject(str(project_parent), "disassemble_entry_points", False)
        imported = project.importProgram(File(str(input_path)))
        if imported is None:
            raise RuntimeError("Ghidra failed to import the fixture executable")
        project.saveAs(imported, "/", input_path.name, True)
        project.save(imported)
        project.close()
        project = None
        project = GhidraProject.openProject(str(project_parent), "disassemble_entry_points", True)
        program = project.openProgram("/", input_path.name, False)
        if program is None:
            raise RuntimeError("Ghidra failed to reopen the saved fixture program")
        before = target_facts(program)
        enabled = configure_analysis(project, program)
        if enabled != [ANALYZER]:
            raise RuntimeError(f"Unexpected enabled analysis options: {enabled}")
        project.analyze(program)
        after = target_facts(program)
        if {row[0] for row in before} != set(TARGETS):
            raise RuntimeError(f"Fixture target lookup is incomplete before analysis: {before}")
        if {row[0] for row in after} != set(TARGETS):
            raise RuntimeError(f"Fixture target lookup is incomplete after analysis: {after}")
        output_path.write_text(report(input_path, enabled, before, after), encoding="utf-8", newline="\n")
        project.save(program)
        print(f"[+] Entry-symbol state before analysis: {before}")
        print(f"[+] Wrote {output_path}")
    finally:
        if project is not None:
            if "program" in locals():
                project.save(program)
            project.close()
        shutil.rmtree(project_parent, ignore_errors=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
