add_library(analyzer_call_fixup_installer STATIC)
target_sources(analyzer_call_fixup_installer PUBLIC FILE_SET cxx_modules TYPE CXX_MODULES FILES src/call_fixup_installer.cppm)
target_link_libraries(analyzer_call_fixup_installer PUBLIC ReCode::AnalyzerShared)
target_compile_features(analyzer_call_fixup_installer PUBLIC cxx_std_23)

if(BUILD_TESTING)
    find_package(GTest CONFIG REQUIRED)
    add_executable(analyzer_call_fixup_installer_tests)
    target_sources(analyzer_call_fixup_installer_tests PRIVATE FILE_SET cxx_modules TYPE CXX_MODULES FILES tests/call_fixup_installer_tests.cppm)
    target_link_libraries(analyzer_call_fixup_installer_tests PRIVATE analyzer_call_fixup_installer ReCode::AnalyzerTestSupport GTest::gtest_main)
    target_compile_features(analyzer_call_fixup_installer_tests PRIVATE cxx_std_23)
    add_test(NAME analyzer_call_fixup_installer_tests COMMAND analyzer_call_fixup_installer_tests)
endif()
