#!/usr/bin/env python3
"""Run Decompiler Parameter ID on explicitly prepared PE functions."""

from __future__ import annotations

import shutil
import sys
import tempfile
from pathlib import Path


ANALYZER = "Decompiler Parameter ID"
DEPENDENCIES: tuple[str, ...] = ()


def address_text(address) -> str:
    """Render a Ghidra address as a stable offset."""
    return f"0x{int(address.getOffset()):016X}"


def configure_analysis(project, program) -> list[str]:
    """Disable unrelated booleans and explicitly retain the target analyzer."""
    from ghidra.framework.options import OptionType

    options = project.getAnalysisOptions(program)
    enabled_names = {ANALYZER, *DEPENDENCIES}
    for name in options.getOptionNames():
        if options.getType(name) == OptionType.BOOLEAN_TYPE:
            options.setBoolean(name, str(name) in enabled_names)
    return sorted(str(name) for name in options.getOptionNames()
                  if options.getType(name) == OptionType.BOOLEAN_TYPE and options.getBoolean(name, False))


def prepare_code(program) -> None:
    """Disassemble executable bytes and create functions at executable PE symbols before analysis."""
    from ghidra.app.cmd.disassemble import DisassembleCommand
    from ghidra.app.cmd.function import CreateFunctionCmd
    from ghidra.program.model.address import AddressSet

    executable = AddressSet()
    for block in program.getMemory().getBlocks():
        if block.isExecute():
            executable.add(block.getStart(), block.getEnd())
    tx = program.startTransaction("Prepare fixture functions")
    committed = False
    try:
        command = DisassembleCommand(executable, executable, False)
        command.enableCodeAnalysis(False)
        if not command.applyTo(program):
            raise RuntimeError(f"Disassembly failed: {command.getStatusMsg()}")
        for symbol in program.getSymbolTable().getAllSymbols(True):
            address = symbol.getAddress()
            if executable.contains(address) and program.getListing().getInstructionAt(address) is not None:
                if program.getFunctionManager().getFunctionAt(address) is None:
                    CreateFunctionCmd(address).applyTo(program)
        committed = True
    finally:
        program.endTransaction(tx, committed)


def parameter_facts(program):
    """Extract parameter count, names, types, and storage from the named fixture function."""
    rows = []
    for function in program.getFunctionManager().getFunctions(True):
        if function.isExternal() or "parameter_fixture" not in function.getName():
            continue
        parameters = []
        for parameter in function.getParameters():
            parameters.append((parameter.getName(), str(parameter.getDataType()), str(parameter.getVariableStorage())))
        rows.append((address_text(function.getEntryPoint()), function.getName(), parameters,
                     str(function.getReturn().getDataType())))
    return sorted(rows)


def report(input_path: Path, enabled: list[str], rows) -> str:
    """Render only the recovered signature facts that the analyzer commits."""
    lines = ["# Decompiler Parameter ID Behavioral Fixture", "",
             "> Generated by PyGhidra; functions were prepared before the target analyzer ran.", "",
             "## Analysis Configuration", "", f"- **Input:** `{input_path.name}`",
             f"- **Enabled boolean analyzers:** `{', '.join(enabled)}`", "", "## Analyzer Discoveries", "",
             "| Function | Name | Return type | Parameter | Type | Storage |", "| --- | --- | --- | --- | --- | --- |"]
    for address, name, parameters, return_type in rows:
        if not parameters:
            lines.append(f"| `{address}` | `{name}` | `{return_type}` | | | |")
        for pname, ptype, storage in parameters:
            lines.append(f"| `{address}` | `{name}` | `{return_type}` | `{pname}` | `{ptype}` | `{storage}` |")
    lines.extend(["", "## Fixture Assertions", "", f"- **Recovered fixture functions:** `{len(rows)}`", ""])
    return "\n".join(lines)


def main() -> int:
    """Create, save, reopen, analyze, save, and close an isolated Ghidra project."""
    fixture_dir = Path(__file__).resolve().parent
    input_path = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else fixture_dir / "test_decompiler_parameter_id.exe"
    output_path = Path(sys.argv[2]).resolve() if len(sys.argv) > 2 else fixture_dir / "test_decompiler_parameter_id.md"
    if not input_path.is_file():
        print(f"Input file does not exist: {input_path}", file=sys.stderr)
        return 2
    import pyghidra

    pyghidra.start()
    from ghidra.base.project import GhidraProject
    from java.io import File

    project_parent = Path(tempfile.mkdtemp(prefix="ghidra_decompiler_parameter_id_"))
    project = None
    try:
        project = GhidraProject.createProject(str(project_parent), "decompiler_parameter_id", False)
        imported = project.importProgram(File(str(input_path)))
        if imported is None:
            raise RuntimeError("Ghidra failed to import the fixture executable")
        project.saveAs(imported, "/", input_path.name, True)
        project.save(imported)
        project.close()
        project = None
        project = GhidraProject.openProject(str(project_parent), "decompiler_parameter_id", True)
        program = project.openProgram("/", input_path.name, False)
        if program is None:
            raise RuntimeError("Ghidra failed to reopen the saved fixture program")
        prepare_code(program)
        enabled = configure_analysis(project, program)
        if enabled != [ANALYZER]:
            raise RuntimeError(f"Unexpected enabled analysis options: {enabled}")
        project.analyze(program)
        output_path.write_text(report(input_path, enabled, parameter_facts(program)), encoding="utf-8", newline="\n")
        project.save(program)
        print(f"[+] Wrote {output_path}")
    finally:
        if project is not None:
            if "program" in locals():
                project.save(program)
            project.close()
        shutil.rmtree(project_parent, ignore_errors=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
