#!/usr/bin/env python3
"""Generate a Ghidra inspection report for the shared body fixture."""

from __future__ import annotations

import shutil
import sys
import tempfile
from pathlib import Path


def main() -> int:
    """Import, disassemble, analyze, and report the dedicated fixture."""
    fixture_dir = Path(__file__).resolve().parent
    input_path = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else fixture_dir / "test_function_body.exe"
    output_path = Path(sys.argv[2]).resolve() if len(sys.argv) > 2 else fixture_dir / "test_function_body.md"
    if not input_path.is_file():
        print(f"Input file does not exist: {input_path}", file=sys.stderr)
        return 2

    import pyghidra

    pyghidra.start()
    from ghidra.app.cmd.disassemble import DisassembleCommand
    from ghidra.base.project import GhidraProject
    from ghidra.program.model.address import AddressSet
    from java.io import File

    project_parent = Path(tempfile.mkdtemp(prefix="ghidra_shared_function_body_"))
    project = None
    try:
        project = GhidraProject.createProject(str(project_parent), "function_body", True)
        imported = project.importProgram(File(str(input_path)))
        if imported is None:
            raise RuntimeError("Ghidra failed to import the function-body fixture")
        project.saveAs(imported, "/", input_path.name, True)
        project.close(imported)
        program = project.openProgram("/", input_path.name, False)
        executable = AddressSet()
        for block in program.getMemory().getBlocks():
            if block.isExecute():
                executable.add(block.getStart(), block.getEnd())
        command = DisassembleCommand(executable, executable, False)
        command.enableCodeAnalysis(False)
        if not command.applyTo(program):
            raise RuntimeError(f"Disassembly failed: {command.getStatusMsg()}")
        from ghidra.framework.options import OptionType

        options = project.getAnalysisOptions(program)
        for name in options.getOptionNames():
            if options.getType(name) == OptionType.BOOLEAN_TYPE:
                options.setBoolean(name, False)
        project.analyze(program)
        functions = sorted(
            f"0x{int(function.getEntryPoint().getOffset()):016X}"
            for function in program.getFunctionManager().getFunctions(True)
            if not function.isExternal()
        )
        instructions = sum(1 for _ in program.getListing().getInstructions(executable, True))
        report = "\n".join(
            [
                "# Shared Function Body Behavioral Fixture",
                "",
                "> Generated by PyGhidra; native tests do not parse this file.",
                "",
                "## Fixture",
                "",
                f"- **Executable:** `{input_path.name}`",
                f"- **Executable instructions:** `{instructions}`",
                f"- **Discovered function entries:** `{functions}`",
                "- The source combines straight-line code, loop/switch flow, a data read, and calls.",
                "- Native body tests construct focused synthetic flow graphs on this real PE/Sleigh context.",
                "",
            ]
        )
        output_path.write_text(report, encoding="utf-8", newline="\n")
        project.save(program)
        print(f"[+] Wrote {output_path}")
    finally:
        if project is not None:
            project.close()
        shutil.rmtree(project_parent, ignore_errors=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
