#!/usr/bin/env python3
"""Run Microsoft Demangler and extract only decorated-symbol transformations."""

from __future__ import annotations

import shutil
import sys
import tempfile
from pathlib import Path


ANALYZER = "Demangler Microsoft"
DEPENDENCIES: tuple[str, ...] = ()


def configure_analysis(project, program) -> list[str]:
    """Disable unrelated boolean analyzers and explicitly enable Microsoft demangling."""
    from ghidra.framework.options import OptionType

    options = project.getAnalysisOptions(program)
    enabled_names = {ANALYZER, *DEPENDENCIES}
    for name in options.getOptionNames():
        if options.getType(name) == OptionType.BOOLEAN_TYPE:
            options.setBoolean(name, str(name) in enabled_names)
    return sorted(str(name) for name in options.getOptionNames()
                  if options.getType(name) == OptionType.BOOLEAN_TYPE and options.getBoolean(name, False))


def prepare_code(program) -> None:
    """Disassemble executable bytes and create functions at PE function symbols."""
    from ghidra.app.cmd.disassemble import DisassembleCommand
    from ghidra.app.cmd.function import CreateFunctionCmd
    from ghidra.program.model.address import AddressSet
    from ghidra.program.model.symbol import SymbolType

    executable = AddressSet()
    for block in program.getMemory().getBlocks():
        if block.isExecute():
            executable.add(block.getStart(), block.getEnd())
    tx = program.startTransaction("Prepare fixture symbols")
    committed = False
    try:
        command = DisassembleCommand(executable, executable, False)
        command.enableCodeAnalysis(False)
        if not command.applyTo(program):
            raise RuntimeError(f"Disassembly failed: {command.getStatusMsg()}")
        for symbol in program.getSymbolTable().getAllSymbols(True):
            address = symbol.getAddress()
            if symbol.getSymbolType() == SymbolType.FUNCTION and executable.contains(address):
                if program.getFunctionManager().getFunctionAt(address) is None:
                    CreateFunctionCmd(address).applyTo(program)
        committed = True
    finally:
        program.endTransaction(tx, committed)


def demangler_facts(program):
    """Pair original Microsoft-decorated names with stable post-analysis symbols/signatures."""
    rows = []
    for symbol in program.getSymbolTable().getAllSymbols(True):
        name = symbol.getName(False)
        if not name.startswith("?"):
            continue
        function = program.getFunctionManager().getFunctionAt(symbol.getAddress())
        rows.append((name, symbol.getAddress(), function))
    result = []
    for mangled, address, function in sorted(rows, key=lambda row: row[0]):
        symbols = sorted(str(item.getName(False)) for item in program.getSymbolTable().getSymbols(address)
                         if not item.getName(False).startswith("?"))
        signature = str(function.getSignature()) if function is not None else "none"
        result.append((mangled, symbols, signature))
    return result


def report(input_path: Path, enabled: list[str], rows) -> str:
    """Render only decorated-name and resulting demangled signature facts."""
    lines = ["# Microsoft Demangler Behavioral Fixture", "",
             "> Generated by PyGhidra from genuine MSVC decorated symbols.", "", "## Analysis Configuration", "",
             f"- **Input:** `{input_path.name}`", f"- **Enabled boolean analyzers:** `{', '.join(enabled)}`", "",
             "## Analyzer Discoveries", "", "| Mangled symbol | Demangled symbols | Function signature |", "| --- | --- | --- |"]
    lines.extend(f"| `{mangled}` | `{', '.join(symbols)}` | `{signature}` |" for mangled, symbols, signature in rows)
    lines.extend(["", "## Fixture Assertions", "", f"- **Decorated symbols processed:** `{len(rows)}`", ""])
    return "\n".join(lines)


def main() -> int:
    """Create, save, reopen, analyze, save, and close an isolated Ghidra project."""
    fixture_dir = Path(__file__).resolve().parent
    input_path = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else fixture_dir / "test_demangler_microsoft.exe"
    output_path = Path(sys.argv[2]).resolve() if len(sys.argv) > 2 else fixture_dir / "test_demangler_microsoft.md"
    if not input_path.is_file():
        print(f"Input file does not exist: {input_path}", file=sys.stderr)
        return 2
    import pyghidra

    pyghidra.start()
    from ghidra.base.project import GhidraProject
    from java.io import File

    project_parent = Path(tempfile.mkdtemp(prefix="ghidra_demangler_microsoft_"))
    project = None
    try:
        project = GhidraProject.createProject(str(project_parent), "demangler_microsoft", False)
        imported = project.importProgram(File(str(input_path)))
        if imported is None:
            raise RuntimeError("Ghidra failed to import the fixture executable")
        project.saveAs(imported, "/", input_path.name, True)
        project.save(imported)
        project.close()
        project = None
        project = GhidraProject.openProject(str(project_parent), "demangler_microsoft", True)
        program = project.openProgram("/", input_path.name, False)
        if program is None:
            raise RuntimeError("Ghidra failed to reopen the saved fixture program")
        prepare_code(program)
        enabled = configure_analysis(project, program)
        if enabled != [ANALYZER]:
            raise RuntimeError(f"Unexpected enabled analysis options: {enabled}")
        project.analyze(program)
        output_path.write_text(report(input_path, enabled, demangler_facts(program)), encoding="utf-8", newline="\n")
        project.save(program)
        print(f"[+] Wrote {output_path}")
    finally:
        if project is not None:
            if "program" in locals():
                project.save(program)
            project.close()
        shutil.rmtree(project_parent, ignore_errors=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
