#!/usr/bin/env python3
"""Run Disassemble Entry Points without pre-disassembling the executable section."""

from __future__ import annotations

import shutil
import sys
import tempfile
from pathlib import Path


ANALYZER = "Disassemble Entry Points"
DEPENDENCIES: tuple[str, ...] = ()
TARGETS = ("entry_point_alpha", "entry_point_beta", "data_only_marker")


def configure_analysis(project, program) -> list[str]:
    """Disable unrelated booleans and explicitly enable the entry-point analyzer."""
    from ghidra.framework.options import OptionType

    options = project.getAnalysisOptions(program)
    enabled_names = {ANALYZER, *DEPENDENCIES}
    for name in options.getOptionNames():
        if options.getType(name) == OptionType.BOOLEAN_TYPE:
            options.setBoolean(name, str(name) in enabled_names)
    return sorted(str(name) for name in options.getOptionNames()
                  if options.getType(name) == OptionType.BOOLEAN_TYPE and options.getBoolean(name, False))


def target_facts(program):
    """Extract symbol, instruction, and function presence for the selected PE entry symbols."""
    rows = []
    symbol_table = program.getSymbolTable()
    for target in TARGETS:
        symbols = [symbol for symbol in symbol_table.getGlobalSymbols(target)]
        for symbol in symbols:
            address = symbol.getAddress()
            rows.append((target, f"0x{int(address.getOffset()):016X}",
                         program.getListing().getInstructionAt(address) is not None,
                         program.getFunctionManager().getFunctionAt(address) is not None))
    return sorted(rows)


def report(input_path: Path, enabled: list[str], rows) -> str:
    """Render only entry-symbol disassembly/function observations."""
    lines = ["# Disassemble Entry Points Behavioral Fixture", "",
             "> Generated by PyGhidra without pre-disassembling executable bytes.", "", "## Analysis Configuration", "",
             f"- **Input:** `{input_path.name}`", f"- **Enabled boolean analyzers:** `{', '.join(enabled)}`", "",
             "## Analyzer Discoveries", "", "| Symbol | Address | Instruction at entry | Function at entry |", "| --- | --- | --- | --- |"]
    lines.extend(f"| `{name}` | `{address}` | `{str(instruction).lower()}` | `{str(function).lower()}` |"
                 for name, address, instruction, function in rows)
    lines.extend(["", "## Fixture Assertions", "", f"- **Selected PE symbols:** `{len(rows)}`", ""])
    return "\n".join(lines)


def main() -> int:
    """Create, save, reopen, analyze, save, and close an isolated Ghidra project."""
    fixture_dir = Path(__file__).resolve().parent
    input_path = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else fixture_dir / "test_disassemble_entry_points.exe"
    output_path = Path(sys.argv[2]).resolve() if len(sys.argv) > 2 else fixture_dir / "test_disassemble_entry_points.md"
    if not input_path.is_file():
        print(f"Input file does not exist: {input_path}", file=sys.stderr)
        return 2
    import pyghidra

    pyghidra.start()
    from ghidra.base.project import GhidraProject
    from java.io import File

    project_parent = Path(tempfile.mkdtemp(prefix="ghidra_disassemble_entry_points_"))
    project = None
    try:
        project = GhidraProject.createProject(str(project_parent), "disassemble_entry_points", False)
        imported = project.importProgram(File(str(input_path)))
        if imported is None:
            raise RuntimeError("Ghidra failed to import the fixture executable")
        project.saveAs(imported, "/", input_path.name, True)
        project.save(imported)
        project.close()
        project = None
        project = GhidraProject.openProject(str(project_parent), "disassemble_entry_points", True)
        program = project.openProgram("/", input_path.name, False)
        if program is None:
            raise RuntimeError("Ghidra failed to reopen the saved fixture program")
        before = target_facts(program)
        enabled = configure_analysis(project, program)
        if enabled != [ANALYZER]:
            raise RuntimeError(f"Unexpected enabled analysis options: {enabled}")
        project.analyze(program)
        after = target_facts(program)
        output_path.write_text(report(input_path, enabled, after), encoding="utf-8", newline="\n")
        project.save(program)
        print(f"[+] Entry-symbol state before analysis: {before}")
        print(f"[+] Wrote {output_path}")
    finally:
        if project is not None:
            if "program" in locals():
                project.save(program)
            project.close()
        shutil.rmtree(project_parent, ignore_errors=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
