// Generated by prepare_bsim_inputs.py for the BSim research experiment.
// Every snippet is exported and marked noinline so PyGhidra can identify one
// stable function body per source file without relying on source filenames.
#pragma optimize("", off)

// Original anonymized snippet: database/abs.cpp
extern "C" __declspec(dllexport) __declspec(noinline) int db_abs(int param_1) {
    if (param_1 < 0) {
        return -param_1;
    }
    return param_1;
}

// Original anonymized snippet: database/atoi.cpp
extern "C" __declspec(dllexport) __declspec(noinline) int db_atoi(const char *param_1) {
    int local_1 = 1;
    int local_2 = 0;
    while (*param_1 == ' ' || *param_1 == '\t' || *param_1 == '\n') {
        ++param_1;
    }
    if (*param_1 == '-' || *param_1 == '+') {
        local_1 = *param_1 == '-' ? -1 : 1;
        ++param_1;
    }
    while (*param_1 >= '0' && *param_1 <= '9') {
        local_2 = local_2 * 10 + (*param_1 - '0');
        ++param_1;
    }
    return local_1 * local_2;
}

// Original anonymized snippet: database/average.cpp
extern "C" __declspec(dllexport) __declspec(noinline) double db_average(const int *param_1, int param_2) {
    if (param_2 == 0) {
        return 0.0;
    }
    long long local_1 = 0;
    for (int local_2 = 0; local_2 < param_2; ++local_2) {
        local_1 += param_1[local_2];
    }
    return static_cast<double>(local_1) / param_2;
}

// Original anonymized snippet: database/binary_search.cpp
extern "C" __declspec(dllexport) __declspec(noinline) bool db_binary_search(const int *param_1, int param_2, int param_3) {
    int local_1 = 0;
    int local_2 = param_2;
    while (local_1 < local_2) {
        int local_3 = local_1 + (local_2 - local_1) / 2;
        if (param_1[local_3] < param_3) {
            local_1 = local_3 + 1;
        } else {
            local_2 = local_3;
        }
    }
    return local_1 < param_2 && param_1[local_1] == param_3;
}

// Original anonymized snippet: database/bsearch.cpp
extern "C" __declspec(dllexport) __declspec(noinline) int db_bsearch(const int *param_1, int param_2, int param_3) {
    int local_1 = 0;
    int local_2 = param_2 - 1;
    while (local_1 <= local_2) {
        int local_3 = local_1 + (local_2 - local_1) / 2;
        if (param_1[local_3] == param_3) {
            return local_3;
        }
        if (param_1[local_3] < param_3) {
            local_1 = local_3 + 1;
        } else {
            local_2 = local_3 - 1;
        }
    }
    return -1;
}

// Original anonymized snippet: database/clamp.cpp
extern "C" __declspec(dllexport) __declspec(noinline) int db_clamp(int param_1, int param_2, int param_3) {
    if (param_1 < param_2) {
        return param_2;
    }
    if (param_1 > param_3) {
        return param_3;
    }
    return param_1;
}

// Original anonymized snippet: database/copy_if.cpp
extern "C" __declspec(dllexport) __declspec(noinline) int db_copy_if(int *param_1, const int *param_2, int param_3, int param_4) {
    int local_1 = 0;
    for (int local_2 = 0; local_2 < param_3; ++local_2) {
        if (param_2[local_2] >= param_4) {
            param_1[local_1] = param_2[local_2];
            ++local_1;
        }
    }
    return local_1;
}

// Original anonymized snippet: database/cos.cpp
extern "C" __declspec(dllexport) __declspec(noinline) double db_cos(double param_1) {
    double local_1 = 1.0;
    double local_2 = 1.0;
    double local_3 = param_1 * param_1;
    for (int local_4 = 1; local_4 <= 8; ++local_4) {
        local_2 = -local_2 * local_3 / ((2 * local_4 - 1) * (2 * local_4));
        local_1 += local_2;
    }
    return local_1;
}

// Original anonymized snippet: database/count_value.cpp
extern "C" __declspec(dllexport) __declspec(noinline) int db_count_value(const int *param_1, int param_2, int param_3) {
    int local_1 = 0;
    for (int local_2 = 0; local_2 < param_2; ++local_2) {
        if (param_1[local_2] == param_3) {
            ++local_1;
        }
    }
    return local_1;
}

// Original anonymized snippet: database/distance_squared.cpp
extern "C" __declspec(dllexport) __declspec(noinline) long long db_distance_squared(const int *param_1, const int *param_2, int param_3) {
    long long local_1 = 0;
    for (int local_2 = 0; local_2 < param_3; ++local_2) {
        long long local_3 = static_cast<long long>(param_1[local_2]) - param_2[local_2];
        local_1 += local_3 * local_3;
    }
    return local_1;
}

// Original anonymized snippet: database/dot_product.cpp
extern "C" __declspec(dllexport) __declspec(noinline) long long db_dot_product(const int *param_1, const int *param_2, int param_3) {
    long long local_1 = 0;
    for (int local_2 = 0; local_2 < param_3; ++local_2) {
        local_1 += static_cast<long long>(param_1[local_2]) * param_2[local_2];
    }
    return local_1;
}

// Original anonymized snippet: database/evaluate_polynomial.cpp
extern "C" __declspec(dllexport) __declspec(noinline) double db_evaluate_polynomial(const double *param_1, int param_2, double param_3) {
    double local_1 = 0.0;
    for (int local_2 = param_2 - 1; local_2 >= 0; --local_2) {
        local_1 = local_1 * param_3 + param_1[local_2];
    }
    return local_1;
}

// Original anonymized snippet: database/factorial.cpp
extern "C" __declspec(dllexport) __declspec(noinline) unsigned long long db_factorial(unsigned int param_1) {
    unsigned long long local_1 = 1;
    for (unsigned int local_2 = 2; local_2 <= param_1; ++local_2) {
        local_1 *= local_2;
    }
    return local_1;
}

// Original anonymized snippet: database/fibonacci.cpp
extern "C" __declspec(dllexport) __declspec(noinline) unsigned long long db_fibonacci(unsigned int param_1) {
    unsigned long long local_1 = 0;
    unsigned long long local_2 = 1;
    for (unsigned int local_3 = 0; local_3 < param_1; ++local_3) {
        unsigned long long local_4 = local_1 + local_2;
        local_1 = local_2;
        local_2 = local_4;
    }
    return local_1;
}

// Original anonymized snippet: database/fill.cpp
extern "C" __declspec(dllexport) __declspec(noinline) void db_fill(int *param_1, int param_2, int param_3) {
    int local_1 = 0;
    while (local_1 < param_2) {
        param_1[local_1] = param_3;
        ++local_1;
    }
}

// Original anonymized snippet: database/first_difference.cpp
extern "C" __declspec(dllexport) __declspec(noinline) int db_first_difference(const int *param_1, const int *param_2, int param_3) {
    for (int local_1 = 0; local_1 < param_3; ++local_1) {
        if (param_1[local_1] != param_2[local_1]) {
            return local_1;
        }
    }
    return -1;
}

// Original anonymized snippet: database/gcd.cpp
extern "C" __declspec(dllexport) __declspec(noinline) int db_gcd(int param_1, int param_2) {
    if (param_1 < 0) {
        param_1 = -param_1;
    }
    if (param_2 < 0) {
        param_2 = -param_2;
    }
    while (param_2 != 0) {
        int local_1 = param_1 % param_2;
        param_1 = param_2;
        param_2 = local_1;
    }
    return param_1;
}

// Original anonymized snippet: database/heap_sort.cpp
extern "C" __declspec(dllexport) __declspec(noinline) void db_heap_sort(int *param_1, int param_2) {
    for (int local_1 = param_2 / 2 - 1; local_1 >= 0; --local_1) {
        int local_2 = local_1;
        while (true) {
            int local_3 = 2 * local_2 + 1;
            if (local_3 >= param_2) {
                break;
            }
            if (local_3 + 1 < param_2 && param_1[local_3] < param_1[local_3 + 1]) {
                ++local_3;
            }
            if (param_1[local_2] >= param_1[local_3]) {
                break;
            }
            int local_4 = param_1[local_2];
            param_1[local_2] = param_1[local_3];
            param_1[local_3] = local_4;
            local_2 = local_3;
        }
    }
    for (int local_5 = param_2 - 1; local_5 > 0; --local_5) {
        int local_6 = param_1[0];
        param_1[0] = param_1[local_5];
        param_1[local_5] = local_6;
        int local_7 = 0;
        while (true) {
            int local_8 = 2 * local_7 + 1;
            if (local_8 >= local_5) {
                break;
            }
            if (local_8 + 1 < local_5 && param_1[local_8] < param_1[local_8 + 1]) {
                ++local_8;
            }
            if (param_1[local_7] >= param_1[local_8]) {
                break;
            }
            int local_9 = param_1[local_7];
            param_1[local_7] = param_1[local_8];
            param_1[local_8] = local_9;
            local_7 = local_8;
        }
    }
}

// Original anonymized snippet: database/iota.cpp
extern "C" __declspec(dllexport) __declspec(noinline) void db_iota(int *param_1, int param_2, int param_3) {
    for (int local_1 = 0; local_1 < param_2; ++local_1) {
        param_1[local_1] = param_3 + local_1;
    }
}

// Original anonymized snippet: database/is_prime.cpp
extern "C" __declspec(dllexport) __declspec(noinline) bool db_is_prime(unsigned int param_1) {
    if (param_1 < 2) {
        return false;
    }
    for (unsigned int local_1 = 2; local_1 <= param_1 / local_1; ++local_1) {
        if (param_1 % local_1 == 0) {
            return false;
        }
    }
    return true;
}

// Original anonymized snippet: database/is_sorted.cpp
extern "C" __declspec(dllexport) __declspec(noinline) bool db_is_sorted(const int *param_1, int param_2) {
    for (int local_1 = 1; local_1 < param_2; ++local_1) {
        if (param_1[local_1] < param_1[local_1 - 1]) {
            return false;
        }
    }
    return true;
}

// Original anonymized snippet: database/lcm.cpp
extern "C" __declspec(dllexport) __declspec(noinline) int db_lcm(int param_1, int param_2) {
    int local_1 = param_1 < 0 ? -param_1 : param_1;
    int local_2 = param_2 < 0 ? -param_2 : param_2;
    int local_3 = local_1;
    int local_4 = local_2;
    while (local_4 != 0) {
        int local_5 = local_3 % local_4;
        local_3 = local_4;
        local_4 = local_5;
    }
    return local_3 == 0 ? 0 : (local_1 / local_3) * local_2;
}

// Original anonymized snippet: database/linear_interpolate.cpp
extern "C" __declspec(dllexport) __declspec(noinline) double db_linear_interpolate(double param_1, double param_2, double param_3, double param_4, double param_5) {
    if (param_2 == param_1) {
        return param_4;
    }
    double local_1 = (param_3 - param_1) / (param_2 - param_1);
    return param_4 + local_1 * (param_5 - param_4);
}

// Original anonymized snippet: database/linear_search.cpp
extern "C" __declspec(dllexport) __declspec(noinline) int db_linear_search(const int *param_1, int param_2, int param_3) {
    for (int local_1 = 0; local_1 < param_2; ++local_1) {
        if (param_1[local_1] == param_3) {
            return local_1;
        }
    }
    return -1;
}

// Original anonymized snippet: database/lower_bound.cpp
extern "C" __declspec(dllexport) __declspec(noinline) int db_lower_bound(const int *param_1, int param_2, int param_3) {
    int local_1 = 0;
    int local_2 = param_2;
    while (local_1 < local_2) {
        int local_3 = local_1 + (local_2 - local_1) / 2;
        if (param_1[local_3] < param_3) {
            local_1 = local_3 + 1;
        } else {
            local_2 = local_3;
        }
    }
    return local_1;
}

// Original anonymized snippet: database/manhattan_distance.cpp
extern "C" __declspec(dllexport) __declspec(noinline) long long db_manhattan_distance(const int *param_1, const int *param_2, int param_3) {
    long long local_1 = 0;
    for (int local_2 = 0; local_2 < param_3; ++local_2) {
        long long local_3 = static_cast<long long>(param_1[local_2]) - param_2[local_2];
        local_1 += local_3 < 0 ? -local_3 : local_3;
    }
    return local_1;
}

// Original anonymized snippet: database/max.cpp
extern "C" __declspec(dllexport) __declspec(noinline) int db_max(int param_1, int param_2) {
    return param_1 > param_2 ? param_1 : param_2;
}

// Original anonymized snippet: database/memcmp.cpp
extern "C" __declspec(dllexport) __declspec(noinline) int db_memcmp(const void *param_1, const void *param_2, int param_3) {
    const unsigned char *local_1 = static_cast<const unsigned char *>(param_1);
    const unsigned char *local_2 = static_cast<const unsigned char *>(param_2);
    for (int local_3 = 0; local_3 < param_3; ++local_3) {
        if (local_1[local_3] != local_2[local_3]) {
            return local_1[local_3] < local_2[local_3] ? -1 : 1;
        }
    }
    return 0;
}

// Original anonymized snippet: database/memcpy.cpp
extern "C" __declspec(dllexport) __declspec(noinline) void *db_memcpy(void *param_1, const void *param_2, int param_3) {
    unsigned char *local_1 = static_cast<unsigned char *>(param_1);
    const unsigned char *local_2 = static_cast<const unsigned char *>(param_2);
    for (int local_3 = 0; local_3 < param_3; ++local_3) {
        local_1[local_3] = local_2[local_3];
    }
    return param_1;
}

// Original anonymized snippet: database/memmove.cpp
extern "C" __declspec(dllexport) __declspec(noinline) void *db_memmove(void *param_1, const void *param_2, int param_3) {
    unsigned char *local_1 = static_cast<unsigned char *>(param_1);
    const unsigned char *local_2 = static_cast<const unsigned char *>(param_2);
    if (local_1 < local_2) {
        for (int local_3 = 0; local_3 < param_3; ++local_3) {
            local_1[local_3] = local_2[local_3];
        }
    } else if (local_1 > local_2) {
        for (int local_3 = param_3; local_3 > 0; --local_3) {
            local_1[local_3 - 1] = local_2[local_3 - 1];
        }
    }
    return param_1;
}

// Original anonymized snippet: database/merge_sorted.cpp
extern "C" __declspec(dllexport) __declspec(noinline) void db_merge_sorted(const int *param_1, int param_2, const int *param_3, int param_4, int *param_5) {
    int local_1 = 0;
    int local_2 = 0;
    int local_3 = 0;
    while (local_1 < param_2 && local_2 < param_4) {
        if (param_1[local_1] <= param_3[local_2]) {
            param_5[local_3] = param_1[local_1];
            ++local_1;
        } else {
            param_5[local_3] = param_3[local_2];
            ++local_2;
        }
        ++local_3;
    }
    while (local_1 < param_2) {
        param_5[local_3] = param_1[local_1];
        ++local_1;
        ++local_3;
    }
    while (local_2 < param_4) {
        param_5[local_3] = param_3[local_2];
        ++local_2;
        ++local_3;
    }
}

// Original anonymized snippet: database/min.cpp
extern "C" __declspec(dllexport) __declspec(noinline) int db_min(int param_1, int param_2) {
    return param_1 < param_2 ? param_1 : param_2;
}

// Original anonymized snippet: database/next_power_of_two.cpp
extern "C" __declspec(dllexport) __declspec(noinline) unsigned int db_next_power_of_two(unsigned int param_1) {
    if (param_1 <= 1) {
        return 1;
    }
    --param_1;
    param_1 |= param_1 >> 1;
    param_1 |= param_1 >> 2;
    param_1 |= param_1 >> 4;
    param_1 |= param_1 >> 8;
    param_1 |= param_1 >> 16;
    return param_1 + 1;
}

// Original anonymized snippet: database/partition.cpp
extern "C" __declspec(dllexport) __declspec(noinline) int db_partition(int *param_1, int param_2, int param_3, int param_4) {
    int local_1 = param_2;
    for (int local_2 = param_2; local_2 < param_3; ++local_2) {
        if (param_1[local_2] < param_4) {
            int local_3 = param_1[local_1];
            param_1[local_1] = param_1[local_2];
            param_1[local_2] = local_3;
            ++local_1;
        }
    }
    return local_1;
}

// Original anonymized snippet: database/pow.cpp
extern "C" __declspec(dllexport) __declspec(noinline) double db_pow(double param_1, int param_2) {
    double local_1 = 1.0;
    int local_2 = param_2 < 0 ? -param_2 : param_2;
    while (local_2 > 0) {
        if ((local_2 & 1) != 0) {
            local_1 *= param_1;
        }
        param_1 *= param_1;
        local_2 >>= 1;
    }
    return param_2 < 0 ? 1.0 / local_1 : local_1;
}

// Original anonymized snippet: database/product_array.cpp
extern "C" __declspec(dllexport) __declspec(noinline) long long db_product_array(const int *param_1, int param_2) {
    long long local_1 = 1;
    for (int local_2 = 0; local_2 < param_2; ++local_2) {
        local_1 *= param_1[local_2];
    }
    return local_1;
}

// Original anonymized snippet: database/qsort.cpp
extern "C" __declspec(dllexport) __declspec(noinline) void db_qsort(int *param_1, int param_2, int param_3) {
    if (param_2 >= param_3) {
        return;
    }
    int local_1 = param_1[param_3];
    int local_2 = param_2;
    for (int local_3 = param_2; local_3 < param_3; ++local_3) {
        if (param_1[local_3] <= local_1) {
            int local_4 = param_1[local_2];
            param_1[local_2] = param_1[local_3];
            param_1[local_3] = local_4;
            ++local_2;
        }
    }
    int local_5 = param_1[local_2];
    param_1[local_2] = param_1[param_3];
    param_1[param_3] = local_5;
    db_qsort(param_1, param_2, local_2 - 1);
    db_qsort(param_1, local_2 + 1, param_3);
}

// Original anonymized snippet: database/remove_value.cpp
extern "C" __declspec(dllexport) __declspec(noinline) int db_remove_value(int *param_1, int param_2, int param_3) {
    int local_1 = 0;
    for (int local_2 = 0; local_2 < param_2; ++local_2) {
        if (param_1[local_2] != param_3) {
            param_1[local_1] = param_1[local_2];
            ++local_1;
        }
    }
    return local_1;
}

// Original anonymized snippet: database/rotate_array.cpp
extern "C" __declspec(dllexport) __declspec(noinline) void db_rotate_array(int *param_1, int param_2, int param_3) {
    if (param_2 == 0) {
        return;
    }
    param_3 %= param_2;
    if (param_3 < 0) {
        param_3 += param_2;
    }
    int local_1 = 0;
    int local_2 = param_3 - 1;
    while (local_1 < local_2) {
        int local_3 = param_1[local_1];
        param_1[local_1] = param_1[local_2];
        param_1[local_2] = local_3;
        ++local_1;
        --local_2;
    }
    local_1 = param_3;
    local_2 = param_2 - 1;
    while (local_1 < local_2) {
        int local_4 = param_1[local_1];
        param_1[local_1] = param_1[local_2];
        param_1[local_2] = local_4;
        ++local_1;
        --local_2;
    }
    local_1 = 0;
    local_2 = param_2 - 1;
    while (local_1 < local_2) {
        int local_5 = param_1[local_1];
        param_1[local_1] = param_1[local_2];
        param_1[local_2] = local_5;
        ++local_1;
        --local_2;
    }
}

// Original anonymized snippet: database/rotate_left.cpp
extern "C" __declspec(dllexport) __declspec(noinline) unsigned int db_rotate_left(unsigned int param_1, unsigned int param_2) {
    param_2 &= 31;
    if (param_2 == 0) {
        return param_1;
    }
    return (param_1 << param_2) | (param_1 >> (32 - param_2));
}

// Original anonymized snippet: database/rotate_right.cpp
extern "C" __declspec(dllexport) __declspec(noinline) unsigned int db_rotate_right(unsigned int param_1, unsigned int param_2) {
    param_2 &= 31;
    if (param_2 == 0) {
        return param_1;
    }
    return (param_1 >> param_2) | (param_1 << (32 - param_2));
}

// Original anonymized snippet: database/sqrt.cpp
extern "C" __declspec(dllexport) __declspec(noinline) double db_sqrt(double param_1) {
    if (param_1 <= 0.0) {
        return 0.0;
    }
    double local_1 = param_1 > 1.0 ? param_1 : 1.0;
    double local_2 = 0.0;
    while (local_1 != local_2) {
        local_2 = local_1;
        local_1 = 0.5 * (local_1 + param_1 / local_1);
        if (local_1 - local_2 < 0.000000001 && local_2 - local_1 < 0.000000001) {
            break;
        }
    }
    return local_1;
}

// Original anonymized snippet: database/strchr.cpp
extern "C" __declspec(dllexport) __declspec(noinline) const char *db_strchr(const char *param_1, char param_2) {
    for (int local_1 = 0;; ++local_1) {
        if (param_1[local_1] == param_2) {
            return param_1 + local_1;
        }
        if (param_1[local_1] == 0) {
            return nullptr;
        }
    }
}

// Original anonymized snippet: database/strcmp.cpp
extern "C" __declspec(dllexport) __declspec(noinline) int db_strcmp(const char *param_1, const char *param_2) {
    int local_1 = 0;
    while (param_1[local_1] != 0 && param_1[local_1] == param_2[local_1]) {
        ++local_1;
    }
    return static_cast<unsigned char>(param_1[local_1]) - static_cast<unsigned char>(param_2[local_1]);
}

// Original anonymized snippet: database/strlen.cpp
extern "C" __declspec(dllexport) __declspec(noinline) int db_strlen(const char *param_1) {
    int local_1 = 0;
    while (param_1[local_1] != 0) {
        ++local_1;
    }
    return local_1;
}

// Original anonymized snippet: database/strstr.cpp
extern "C" __declspec(dllexport) __declspec(noinline) const char *db_strstr(const char *param_1, const char *param_2) {
    if (param_2[0] == 0) {
        return param_1;
    }
    for (int local_1 = 0; param_1[local_1] != 0; ++local_1) {
        int local_2 = 0;
        while (param_1[local_1 + local_2] != 0 && param_2[local_2] != 0 && param_1[local_1 + local_2] == param_2[local_2]) {
            ++local_2;
        }
        if (param_2[local_2] == 0) {
            return param_1 + local_1;
        }
    }
    return nullptr;
}

// Original anonymized snippet: database/sum_array.cpp
extern "C" __declspec(dllexport) __declspec(noinline) long long db_sum_array(const int *param_1, int param_2) {
    long long local_1 = 0;
    for (int local_2 = 0; local_2 < param_2; ++local_2) {
        local_1 += param_1[local_2];
    }
    return local_1;
}

// Original anonymized snippet: database/swap_ranges.cpp
extern "C" __declspec(dllexport) __declspec(noinline) void db_swap_ranges(int *param_1, int *param_2, int param_3) {
    for (int local_1 = 0; local_1 < param_3; ++local_1) {
        int local_2 = param_1[local_1];
        param_1[local_1] = param_2[local_1];
        param_2[local_1] = local_2;
    }
}

// Original anonymized snippet: database/unique.cpp
extern "C" __declspec(dllexport) __declspec(noinline) int db_unique(int *param_1, int param_2) {
    if (param_2 == 0) {
        return 0;
    }
    int local_1 = 1;
    for (int local_2 = 1; local_2 < param_2; ++local_2) {
        if (param_1[local_2] != param_1[local_1 - 1]) {
            param_1[local_1] = param_1[local_2];
            ++local_1;
        }
    }
    return local_1;
}

// Original anonymized snippet: database/upper_bound.cpp
extern "C" __declspec(dllexport) __declspec(noinline) int db_upper_bound(const int *param_1, int param_2, int param_3) {
    int local_1 = 0;
    int local_2 = param_2;
    while (local_1 < local_2) {
        int local_3 = local_1 + (local_2 - local_1) / 2;
        if (param_3 < param_1[local_3]) {
            local_2 = local_3;
        } else {
            local_1 = local_3 + 1;
        }
    }
    return local_1;
}

// The executable entry point is intentionally inert; exported snippets
// are the only functions consumed by the PyGhidra BSim experiment.
int main() {
    return 0;
}
