// Generated by prepare_bsim_inputs.py for the BSim research experiment.
// Every snippet is exported and marked noinline so PyGhidra can identify one
// stable function body per source file without relying on source filenames.
#pragma optimize("", off)

// Original anonymized snippet: input/01_bsearch_variant.cpp
extern "C" __declspec(dllexport) __declspec(noinline) int input_01_bsearch_variant(const int *param_1, int param_2, int param_3) {
    int local_1 = 0;
    int local_2 = param_2;
    while (local_1 < local_2) {
        int local_3 = local_1 + (local_2 - local_1) / 2;
        if (param_3 <= param_1[local_3]) {
            local_2 = local_3;
        } else {
            local_1 = local_3 + 1;
        }
    }
    if (local_1 != param_2 && param_1[local_1] == param_3) {
        return local_1;
    }
    return -1;
}

// Original anonymized snippet: input/02_qsort_variant.cpp
extern "C" __declspec(dllexport) __declspec(noinline) void input_02_qsort_variant(int *param_1, int param_2) {
    for (int local_1 = 1; local_1 < param_2; ++local_1) {
        int local_2 = param_1[local_1];
        int local_3 = local_1;
        while (local_3 > 0 && param_1[local_3 - 1] > local_2) {
            param_1[local_3] = param_1[local_3 - 1];
            --local_3;
        }
        param_1[local_3] = local_2;
    }
}

// Original anonymized snippet: input/03_strlen_variant.cpp
extern "C" __declspec(dllexport) __declspec(noinline) int input_03_strlen_variant(const char *param_1) {
    const char *local_1 = param_1;
    while (*local_1) {
        ++local_1;
    }
    return static_cast<int>(local_1 - param_1);
}

// Original anonymized snippet: input/04_strcmp_variant.cpp
extern "C" __declspec(dllexport) __declspec(noinline) int input_04_strcmp_variant(const char *param_1, const char *param_2) {
    while (*param_1 && *param_1 == *param_2) {
        ++param_1;
        ++param_2;
    }
    if (static_cast<unsigned char>(*param_1) < static_cast<unsigned char>(*param_2)) {
        return -1;
    }
    if (static_cast<unsigned char>(*param_1) > static_cast<unsigned char>(*param_2)) {
        return 1;
    }
    return 0;
}

// Original anonymized snippet: input/05_memmove_variant.cpp
extern "C" __declspec(dllexport) __declspec(noinline) void *input_05_memmove_variant(void *param_1, const void *param_2, int param_3) {
    unsigned char *local_1 = static_cast<unsigned char *>(param_1);
    const unsigned char *local_2 = static_cast<const unsigned char *>(param_2);
    if (local_1 == local_2 || param_3 == 0) {
        return param_1;
    }
    if (local_1 < local_2) {
        int local_3 = 0;
        while (local_3 < param_3) {
            local_1[local_3] = local_2[local_3];
            ++local_3;
        }
    } else {
        int local_3 = param_3;
        while (local_3 != 0) {
            --local_3;
            local_1[local_3] = local_2[local_3];
        }
    }
    return param_1;
}

// Original anonymized snippet: input/06_gcd_variant.cpp
extern "C" __declspec(dllexport) __declspec(noinline) int input_06_gcd_variant(int param_1, int param_2) {
    if (param_1 < 0) {
        param_1 = -param_1;
    }
    if (param_2 < 0) {
        param_2 = -param_2;
    }
    while (param_1 != param_2) {
        if (param_1 > param_2) {
            param_1 -= param_2;
        } else {
            param_2 -= param_1;
        }
    }
    return param_1;
}

// Original anonymized snippet: input/07_clamp_variant.cpp
extern "C" __declspec(dllexport) __declspec(noinline) int input_07_clamp_variant(int param_1, int param_2, int param_3) {
    return param_1 < param_2 ? param_2 : param_1 > param_3 ? param_3 : param_1;
}

// Original anonymized snippet: input/08_NONE_prefix_sum.cpp
extern "C" __declspec(dllexport) __declspec(noinline) void input_08_NONE_prefix_sum(int *param_1, int param_2) {
    int local_1 = 0;
    for (int local_2 = 0; local_2 < param_2; ++local_2) {
        local_1 += param_1[local_2];
        param_1[local_2] = local_1;
    }
}

// Original anonymized snippet: input/09_NONE_count_bits.cpp
extern "C" __declspec(dllexport) __declspec(noinline) int input_09_NONE_count_bits(unsigned int param_1) {
    int local_1 = 0;
    while (param_1 != 0) {
        param_1 &= param_1 - 1;
        ++local_1;
    }
    return local_1;
}

// Original anonymized snippet: input/10_NONE_reverse.cpp
extern "C" __declspec(dllexport) __declspec(noinline) void input_10_NONE_reverse(int *param_1, int param_2) {
    int local_1 = 0;
    int local_2 = param_2 - 1;
    while (local_1 < local_2) {
        int local_3 = param_1[local_1];
        param_1[local_1] = param_1[local_2];
        param_1[local_2] = local_3;
        ++local_1;
        --local_2;
    }
}

// The executable entry point is intentionally inert; exported snippets
// are the only functions consumed by the PyGhidra BSim experiment.
int main() {
    return 0;
}
