#!/usr/bin/env python3
"""Combine anonymized research snippets into two exported PE fixtures."""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent


def combine_sources(directory: Path, prefix: str, output: Path) -> list[str]:
    """Rename each ``func_1`` snippet and emit one independently exported source file."""
    fragments: list[str] = []
    symbols: list[str] = []
    for source_path in sorted(directory.glob("*.cpp")):
        stem = re.sub(r"[^A-Za-z0-9_]", "_", source_path.stem)
        symbol = f"{prefix}_{stem}"
        source = source_path.read_text(encoding="utf-8")
        source = re.sub(r"\bfunc_1\b", symbol, source)
        source = (
            f"// Original anonymized snippet: {directory.name}/{source_path.name}\n"
            f"extern \"C\" __declspec(dllexport) __declspec(noinline) {source.strip()}\n"
        )
        fragments.append(source)
        symbols.append(symbol)

    if not fragments:
        raise RuntimeError(f"No C++ snippets found in {directory}")

    header = """// Generated by prepare_bsim_inputs.py for the BSim research experiment.
// Every snippet is exported and marked noinline so PyGhidra can identify one
// stable function body per source file without relying on source filenames.
#pragma optimize(\"\", off)

"""
    main = """// The executable entry point is intentionally inert; exported snippets
// are the only functions consumed by the PyGhidra BSim experiment.
int main() {
    return 0;
}
"""
    output.write_text(header + "\n".join(fragments) + "\n" + main, encoding="utf-8", newline="\n")
    return symbols


def main() -> int:
    """Generate the combined database.cpp and input.cpp fixtures in this directory."""
    database_symbols = combine_sources(ROOT / "database", "db", ROOT / "database.cpp")
    input_symbols = combine_sources(ROOT / "input", "input", ROOT / "input.cpp")
    (ROOT / "bsim_symbol_manifest.txt").write_text(
        "[database]\n" + "\n".join(database_symbols) + "\n\n[input]\n" + "\n".join(input_symbols) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"Generated database.cpp with {len(database_symbols)} exported functions")
    print(f"Generated input.cpp with {len(input_symbols)} exported functions")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
