add_library(new_ghidra_function_id_service STATIC)
target_sources(new_ghidra_function_id_service PUBLIC
    FILE_SET cxx_modules TYPE CXX_MODULES FILES function_id_service.cppm types.cppm database_resource.cppm
)
add_library(NewGhidra::FunctionIdService ALIAS new_ghidra_function_id_service)
target_link_libraries(new_ghidra_function_id_service PUBLIC NewGhidra::Core NewGhidra::RuntimeWorkers function_id)
target_compile_features(new_ghidra_function_id_service PUBLIC cxx_std_23)
