#!/usr/bin/env python3
"""Run Data Reference with its Reference prerequisite and extract data-origin facts."""

from __future__ import annotations

import shutil
import sys
import tempfile
from pathlib import Path


ANALYZER = "Data Reference"
DEPENDENCIES = ("Reference",)


def address_text(address) -> str:
    """Render a Ghidra address as an image-base-independent offset."""
    return f"0x{int(address.getOffset()):016X}"


def configure_analysis(project, program) -> list[str]:
    """Disable unrelated booleans while retaining the analyzer's reference prerequisite."""
    from ghidra.framework.options import OptionType

    options = project.getAnalysisOptions(program)
    enabled_names = {ANALYZER, *DEPENDENCIES}
    for name in options.getOptionNames():
        if options.getType(name) == OptionType.BOOLEAN_TYPE:
            options.setBoolean(name, str(name) in enabled_names)
    # Preserve the Reference analyzer's relocation-guided pointer behavior; this is a
    # nested analyzer option rather than a top-level boolean returned by getAnalysisOptions().
    analysis_properties = program.getOptions("Analysis")
    analysis_properties.getOptions("Reference").setBoolean("Relocation Table Guide", True)
    return sorted(str(name) for name in options.getOptionNames()
                  if options.getType(name) == OptionType.BOOLEAN_TYPE and options.getBoolean(name, False))


def data_reference_facts(program):
    """Extract only references whose source code unit is data and the resulting data type."""
    listing = program.getListing()
    source_addresses = set()
    pointer_size = program.getDefaultPointerSize()
    for symbol in program.getSymbolTable().getGlobalSymbols("fixture_pointer_data"):
        base = symbol.getAddress()
        source_data = listing.getDataContaining(base)
        length = max(source_data.getLength() if source_data is not None else 0, pointer_size * 2)
        source_addresses.update(base.add(offset) for offset in range(0, length, pointer_size))
    rows = []
    reference_manager = program.getReferenceManager()
    for source in sorted(source_addresses, key=lambda address: int(address.getOffset())):
        for reference in reference_manager.getReferencesFrom(source):
            target = listing.getDataContaining(reference.getToAddress())
            if target is not None:
                datatype = " ".join(str(target.getDataType()).split()).replace("|", "\\|")
                rows.append((address_text(source), address_text(reference.getToAddress()),
                              datatype, target.getLength()))
    return sorted(set(rows))


def report(input_path: Path, enabled: list[str], rows) -> str:
    """Render stable data-origin reference facts without reporting unrelated analysis output."""
    lines = [
        "# Data Reference Behavioral Fixture", "",
        "> Generated by PyGhidra with `Reference` retained as the prerequisite.", "",
        "## Analysis Configuration", "",
        f"- **Input:** `{input_path.name}`",
        f"- **Enabled boolean analyzers:** `{', '.join(enabled)}`", "",
        "## Analyzer Discoveries", "",
        "| Data source | Referenced address | Resulting data type | Length |",
        "| --- | --- | --- | ---: |",
    ]
    lines.extend(f"| `{source}` | `{target}` | `{datatype}` | `{length}` |"
                 for source, target, datatype, length in rows)
    lines.extend(["", "## Fixture Assertions", "", f"- **Data-origin references with defined targets:** `{len(rows)}`", ""])
    return "\n".join(lines)


def main() -> int:
    """Create, save, reopen, analyze, save, and close an isolated Ghidra project."""
    fixture_dir = Path(__file__).resolve().parent
    input_path = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else fixture_dir / "test_data_reference.exe"
    output_path = Path(sys.argv[2]).resolve() if len(sys.argv) > 2 else fixture_dir / "test_data_reference.md"
    if not input_path.is_file():
        print(f"Input file does not exist: {input_path}", file=sys.stderr)
        return 2
    import pyghidra

    pyghidra.start()
    from ghidra.app.cmd.disassemble import DisassembleCommand
    from ghidra.base.project import GhidraProject
    from ghidra.program.model.address import AddressSet
    from java.io import File

    project_parent = Path(tempfile.mkdtemp(prefix="ghidra_data_reference_"))
    project = None
    try:
        project = GhidraProject.createProject(str(project_parent), "data_reference", False)
        imported = project.importProgram(File(str(input_path)))
        if imported is None:
            raise RuntimeError("Ghidra failed to import the fixture executable")
        project.saveAs(imported, "/", input_path.name, True)
        project.save(imported)
        project.close()
        project = None
        project = GhidraProject.openProject(str(project_parent), "data_reference", True)
        program = project.openProgram("/", input_path.name, False)
        if program is None:
            raise RuntimeError("Ghidra failed to reopen the saved fixture program")
        executable = AddressSet()
        for block in program.getMemory().getBlocks():
            if block.isExecute():
                executable.add(block.getStart(), block.getEnd())
        tx = program.startTransaction("Prepare fixture disassembly")
        committed = False
        try:
            command = DisassembleCommand(executable, executable, False)
            command.enableCodeAnalysis(False)
            if not command.applyTo(program):
                raise RuntimeError(f"Disassembly failed: {command.getStatusMsg()}")
            committed = True
        finally:
            program.endTransaction(tx, committed)
        enabled = configure_analysis(project, program)
        expected = sorted({ANALYZER, *DEPENDENCIES})
        if enabled != expected:
            raise RuntimeError(f"Unexpected enabled analysis options: {enabled}")
        project.analyze(program)
        output_path.write_text(report(input_path, enabled, data_reference_facts(program)), encoding="utf-8", newline="\n")
        project.save(program)
        print(f"[+] Wrote {output_path}")
    finally:
        if project is not None:
            if "program" in locals():
                project.save(program)
            project.close()
        shutil.rmtree(project_parent, ignore_errors=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
