#!/usr/bin/env python3
"""Generate a human-readable Ghidra report for the constant fixture."""

from __future__ import annotations

import shutil
import sys
import tempfile
from pathlib import Path


ANALYZER_NAME = "Constant Propagation"


def address_text(address) -> str:
    """Render a stable Ghidra address offset."""
    return f"0x{int(address.getOffset()):016X}"


def main() -> int:
    """Import, isolate, analyze, and report the real constant fixture."""
    fixture_dir = Path(__file__).resolve().parent
    input_path = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else fixture_dir / "test_constant_propagation.exe"
    output_path = Path(sys.argv[2]).resolve() if len(sys.argv) > 2 else fixture_dir / "test_constant_propagation.md"
    if not input_path.is_file():
        print(f"Input file does not exist: {input_path}", file=sys.stderr)
        return 2

    import pyghidra

    pyghidra.start()
    from ghidra.base.project import GhidraProject
    from ghidra.app.cmd.disassemble import DisassembleCommand
    from ghidra.program.model.address import AddressSet
    from java.io import File

    project_parent = Path(tempfile.mkdtemp(prefix="ghidra_constant_propagation_"))
    project = None
    try:
        project = GhidraProject.createProject(str(project_parent), "constant_propagation", True)
        program = project.importProgram(File(str(input_path)))
        if program is None:
            raise RuntimeError("Ghidra failed to import the constant fixture")
        project.saveAs(program, "/", input_path.name, True)
        project.close(program)
        program = project.openProgram("/", input_path.name, False)
        executable = AddressSet()
        for block in program.getMemory().getBlocks():
            if block.isExecute():
                executable.add(block.getStart(), block.getEnd())
        transaction = program.startTransaction("Prepare constant fixture")
        committed = False
        try:
            command = DisassembleCommand(executable, executable, False)
            command.enableCodeAnalysis(False)
            if not command.applyTo(program):
                raise RuntimeError(f"Disassembly failed: {command.getStatusMsg()}")
            committed = True
        finally:
            program.endTransaction(transaction, committed)

        options = project.getAnalysisOptions(program)
        for name in options.getOptionNames():
            if options.getType(name).toString() == "BOOLEAN_TYPE":
                options.setBoolean(name, str(name) == ANALYZER_NAME)
        before = sorted(
            address_text(function.getEntryPoint())
            for function in program.getFunctionManager().getFunctions(True)
            if not function.isExternal()
        )
        project.analyze(program)
        after = sorted(
            address_text(function.getEntryPoint())
            for function in program.getFunctionManager().getFunctions(True)
            if not function.isExternal()
        )
        report = "\n".join(
            [
                "# Constant Propagation Behavioral Fixture",
                "",
                "> Generated by PyGhidra; the native tests do not parse this file.",
                "",
                "## Input",
                "",
                f"- **Executable:** `{input_path.name}`",
                f"- **Enabled analyzer:** `{ANALYZER_NAME}`",
                "",
                "## Function Entries Before Analysis",
                "",
                *[f"- `{entry}`" for entry in before],
                "",
                "## Function Entries After Analysis",
                "",
                *[f"- `{entry}`" for entry in after],
                "",
                "## Delta",
                "",
                f"- **Entries before:** `{len(before)}`",
                f"- **Entries after:** `{len(after)}`",
                f"- **New entries:** `{sorted(set(after) - set(before))}`",
                "- The fixture exercises loop/switch propagation, conditional joins, and global memory stores.",
                "",
            ]
        )
        project.save(program)
        output_path.write_text(report, encoding="utf-8", newline="\n")
        print(f"[+] Wrote {output_path}")
    finally:
        if project is not None:
            project.close()
        shutil.rmtree(project_parent, ignore_errors=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
