module;

/* ###
 * IP: GHIDRA
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/// \file error.cppm
/// \brief Base class for error handling facilities
///
/// This is also doubles as a place to list the common include files

#ifndef __ERROR_HH__
#define __ERROR_HH__

#include <algorithm>
#include <cctype>
#include <cstring>
#include <deque>
#include <fstream>
#include <iomanip>
#include <list>
#include <map>
#include <memory>
#include <set>
#include <sstream>
#include <vector>

export module sleigh_runtime.ghidra:error;

export import :types;

export namespace ghidra {

using std::dec;
using std::deque;
using std::endl;
using std::hex;
using std::ifstream;
using std::ios;
using std::istream;
using std::istringstream;
using std::list;
using std::make_pair;
using std::map;
using std::max;
using std::min;
using std::oct;
using std::ostream;
using std::ostringstream;
using std::pair;
using std::set;
using std::setfill;
using std::setw;
using std::string;
using std::to_string;
using std::unique_ptr;
using std::vector;

/// \brief The lowest level error generated by the decompiler
///
/// This is the base error for all exceptions thrown by the
/// decompiler.  This underived form is thrown for very low
/// level errors that immediately abort decompilation (usually
/// for just a single function).
struct LowlevelError {
    string explain; ///< Explanatory string
    /// Initialize the error with an explanatory string
    LowlevelError(const string& s) {
        explain = s;
    }
};

} // End namespace ghidra
#endif
