#!/usr/bin/env python3
"""Run only Ghidra's Create Address Tables analyzer and extract its bookmarks/data."""

from __future__ import annotations

import shutil
import sys
import tempfile
from pathlib import Path


ANALYZER = "Create Address Tables"
DEPENDENCIES: tuple[str, ...] = ()


def address_text(address) -> str:
    """Render an address as an image-base-independent fixed-width offset."""
    return f"0x{int(address.getOffset()):016X}"


def configure_analysis(project, program) -> list[str]:
    """Disable unrelated boolean options and preserve declared dependencies."""
    from ghidra.framework.options import OptionType

    options = project.getAnalysisOptions(program)
    enabled_names = {ANALYZER, *DEPENDENCIES}
    for name in options.getOptionNames():
        if options.getType(name) == OptionType.BOOLEAN_TYPE:
            options.setBoolean(name, str(name) in enabled_names)
    return sorted(
        str(name)
        for name in options.getOptionNames()
        if options.getType(name) == OptionType.BOOLEAN_TYPE
        and options.getBoolean(name, False)
    )


def fixture_table_range(program) -> tuple[int, int]:
    """Return the exact exported fixture-table range, excluding the sentinel."""
    table = next(iter(program.getSymbolTable().getGlobalSymbols("fixture_table")), None)
    after = next(iter(program.getSymbolTable().getGlobalSymbols("fixture_after_table")), None)
    if table is None or after is None:
        raise RuntimeError("Exported fixture table boundary symbols were not imported")
    start = int(table.getAddress().getOffset())
    end = int(after.getAddress().getOffset()) - 1
    if end < start:
        raise RuntimeError(f"Invalid fixture table range: {start:#x}..{end:#x}")
    return start, end


def table_facts(program, table_range: tuple[int, int]) -> list[tuple[str, int, str]]:
    """Extract only bookmark/pointer facts inside the actual fixture table range."""
    start, end = table_range
    facts = []
    bookmarks = program.getBookmarkManager().getBookmarksIterator()
    while bookmarks.hasNext():
        bookmark = bookmarks.next()
        address = int(bookmark.getAddress().getOffset())
        if (bookmark.getTypeString() == "Analysis" and bookmark.getCategory() == "Address Table"
                and start <= address <= end):
            facts.append((address_text(bookmark.getAddress()), -1, bookmark.getComment()))
    data = program.getListing().getDefinedData(program.getMemory().getLoadedAndInitializedAddressSet(), True)
    while data.hasNext():
        item = data.next()
        address = int(item.getAddress().getOffset())
        if item.isPointer() and start <= address <= end:
            facts.append((address_text(item.getAddress()), item.getLength(), "pointer"))
    return sorted(facts)


def fact_delta(before, after):
    """Compare table facts by address and classify additions, removals, and changes."""
    before_by_address = {row[0]: row for row in before}
    after_by_address = {row[0]: row for row in after}
    added = [after_by_address[key] for key in sorted(set(after_by_address) - set(before_by_address))]
    removed = [before_by_address[key] for key in sorted(set(before_by_address) - set(after_by_address))]
    changed = [(before_by_address[key], after_by_address[key])
               for key in sorted(set(before_by_address) & set(after_by_address))
               if before_by_address[key] != after_by_address[key]]
    return added, removed, changed


def delta_lines(before, after) -> list[str]:
    """Render explicit table-fact delta rows, including the no-change case."""
    added, removed, changed = fact_delta(before, after)
    if not added and not removed and not changed:
        return ["## Delta", "", "No changes observed", ""]

    def row_text(row) -> str:
        """Render one table fact for a delta list."""
        address, length, comment = row
        return f"`{address}` | length `{length}` | `{comment}`"

    lines = ["## Delta", "", "### Added rows", ""]
    if added:
        lines.extend(f"- {row_text(row)}" for row in added)
    else:
        lines.append("- None")
    lines.extend(["", "### Removed rows", ""])
    if removed:
        lines.extend(f"- {row_text(row)}" for row in removed)
    else:
        lines.append("- None")
    lines.extend(["", "### Changed rows", ""])
    if changed:
        lines.extend(f"- {row_text(old)} -> {row_text(new)}" for old, new in changed)
    else:
        lines.append("- None")
    lines.append("")
    return lines


def report(input_path: Path, enabled: list[str], table_range, before, after) -> str:
    """Render phase snapshots and an explicit delta within the fixture-table range."""
    start, end = table_range
    lines = [
        "# Create Address Tables Behavioral Fixture",
        "",
        "> Generated by PyGhidra; unrelated boolean analyzers were disabled.",
        "",
        "## Analysis Configuration",
        "",
        f"- **Input:** `{input_path.name}`",
        f"- **Enabled boolean analyzers:** `{', '.join(enabled)}`",
        f"- **Fixture table range:** `0x{start:016X}` through `0x{end:016X}` (the exported sentinel begins immediately afterward).",
        "",
        "## Before target analysis",
        "",
        "| Address | Length | Kind or bookmark comment |",
        "| --- | ---: | --- |",
    ]
    lines.extend(f"| `{addr}` | `{length}` | `{comment}` |" for addr, length, comment in before)
    lines.extend(["", "## After target analysis", "", "| Address | Length | Kind or bookmark comment |", "| --- | ---: | --- |"])
    lines.extend(f"| `{addr}` | `{length}` | `{comment}` |" for addr, length, comment in after)
    lines.extend(["", "## Fixture Assertions", "", f"- **Facts before analysis in fixture range:** `{len(before)}`", f"- **Facts after analysis in fixture range:** `{len(after)}`", "- Pointer metadata outside the exported table range is intentionally excluded from this report.", ""])
    lines.extend(delta_lines(before, after))
    return "\n".join(lines)


def main() -> int:
    """Create, save, reopen, analyze, save, and close an isolated Ghidra project."""
    fixture_dir = Path(__file__).resolve().parent
    input_path = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else fixture_dir / "test_create_address_tables.exe"
    output_path = Path(sys.argv[2]).resolve() if len(sys.argv) > 2 else fixture_dir / "test_create_address_tables.md"
    if not input_path.is_file():
        print(f"Input file does not exist: {input_path}", file=sys.stderr)
        return 2

    import pyghidra

    pyghidra.start()
    from ghidra.app.cmd.disassemble import DisassembleCommand
    from ghidra.base.project import GhidraProject
    from ghidra.program.model.address import AddressSet
    from java.io import File

    project_parent = Path(tempfile.mkdtemp(prefix="ghidra_create_address_tables_"))
    project_name = "create_address_tables"
    program_name = input_path.name
    project = None
    try:
        project = GhidraProject.createProject(str(project_parent), project_name, False)
        imported = project.importProgram(File(str(input_path)))
        if imported is None:
            raise RuntimeError("Ghidra failed to import the fixture executable")
        project.saveAs(imported, "/", program_name, True)
        project.save(imported)
        project.close()
        project = None
        project = GhidraProject.openProject(str(project_parent), project_name, True)
        program = project.openProgram("/", program_name, False)
        if program is None:
            raise RuntimeError("Ghidra failed to reopen the saved fixture program")

        executable = AddressSet()
        for block in program.getMemory().getBlocks():
            if block.isExecute():
                executable.add(block.getStart(), block.getEnd())
        tx = program.startTransaction("Prepare fixture disassembly")
        committed = False
        try:
            command = DisassembleCommand(executable, executable, False)
            command.enableCodeAnalysis(False)
            if not command.applyTo(program):
                raise RuntimeError(f"Disassembly failed: {command.getStatusMsg()}")
            committed = True
        finally:
            program.endTransaction(tx, committed)

        table_range = fixture_table_range(program)
        before = table_facts(program, table_range)
        enabled = configure_analysis(project, program)
        expected = sorted({ANALYZER, *DEPENDENCIES})
        if enabled != expected:
            raise RuntimeError(f"Unexpected enabled analysis options: {enabled}")
        project.analyze(program)
        after = table_facts(program, table_range)
        if not after or any(int(address, 16) < table_range[0] or int(address, 16) > table_range[1]
                            for address, _, _ in after):
            raise RuntimeError(f"No confined fixture table facts were created: before={before}, after={after}")
        output_path.write_text(report(input_path, enabled, table_range, before, after), encoding="utf-8", newline="\n")
        project.save(program)
        print(f"[+] Wrote {output_path}")
    finally:
        if project is not None:
            if "program" in locals():
                project.save(program)
            project.close()
        shutil.rmtree(project_parent, ignore_errors=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
