#!/usr/bin/env python3
"""Run only Ghidra's Create Address Tables analyzer and extract its bookmarks/data."""

from __future__ import annotations

import shutil
import sys
import tempfile
from pathlib import Path


ANALYZER = "Create Address Tables"
DEPENDENCIES: tuple[str, ...] = ()


def address_text(address) -> str:
    """Render an address as an image-base-independent fixed-width offset."""
    return f"0x{int(address.getOffset()):016X}"


def configure_analysis(project, program) -> list[str]:
    """Disable unrelated boolean options and preserve declared dependencies."""
    from ghidra.framework.options import OptionType

    options = project.getAnalysisOptions(program)
    enabled_names = {ANALYZER, *DEPENDENCIES}
    for name in options.getOptionNames():
        if options.getType(name) == OptionType.BOOLEAN_TYPE:
            options.setBoolean(name, str(name) in enabled_names)
    return sorted(
        str(name)
        for name in options.getOptionNames()
        if options.getType(name) == OptionType.BOOLEAN_TYPE
        and options.getBoolean(name, False)
    )


def table_facts(program) -> list[tuple[str, int, str]]:
    """Extract Address Table bookmarks and pointer data created by the target analyzer."""
    facts = []
    bookmarks = program.getBookmarkManager().getBookmarksIterator()
    while bookmarks.hasNext():
        bookmark = bookmarks.next()
        if bookmark.getTypeString() == "Analysis" and bookmark.getCategory() == "Address Table":
            facts.append((address_text(bookmark.getAddress()), -1, bookmark.getComment()))
    data = program.getListing().getDefinedData(program.getMemory().getLoadedAndInitializedAddressSet(), True)
    while data.hasNext():
        item = data.next()
        if item.isPointer():
            facts.append((address_text(item.getAddress()), item.getLength(), "pointer"))
    return sorted(facts)


def report(input_path: Path, enabled: list[str], facts) -> str:
    """Render only stable table-bookmark and pointer-data observations."""
    lines = [
        "# Create Address Tables Behavioral Fixture",
        "",
        "> Generated by PyGhidra; unrelated boolean analyzers were disabled.",
        "",
        "## Analysis Configuration",
        "",
        f"- **Input:** `{input_path.name}`",
        f"- **Enabled boolean analyzers:** `{', '.join(enabled)}`",
        "",
        "## Analyzer Discoveries",
        "",
        "| Address | Length | Kind or bookmark comment |",
        "| --- | ---: | --- |",
    ]
    lines.extend(f"| `{addr}` | `{length}` | `{comment}` |" for addr, length, comment in facts)
    lines.extend(["", "## Fixture Assertions", "", f"- **Stable analyzer facts:** `{len(facts)}`", ""])
    return "\n".join(lines)


def main() -> int:
    """Create, save, reopen, analyze, save, and close an isolated Ghidra project."""
    fixture_dir = Path(__file__).resolve().parent
    input_path = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else fixture_dir / "test_create_address_tables.exe"
    output_path = Path(sys.argv[2]).resolve() if len(sys.argv) > 2 else fixture_dir / "test_create_address_tables.md"
    if not input_path.is_file():
        print(f"Input file does not exist: {input_path}", file=sys.stderr)
        return 2

    import pyghidra

    pyghidra.start()
    from ghidra.app.cmd.disassemble import DisassembleCommand
    from ghidra.base.project import GhidraProject
    from ghidra.program.model.address import AddressSet
    from java.io import File

    project_parent = Path(tempfile.mkdtemp(prefix="ghidra_create_address_tables_"))
    project_name = "create_address_tables"
    program_name = input_path.name
    project = None
    try:
        project = GhidraProject.createProject(str(project_parent), project_name, False)
        imported = project.importProgram(File(str(input_path)))
        if imported is None:
            raise RuntimeError("Ghidra failed to import the fixture executable")
        project.saveAs(imported, "/", program_name, True)
        project.save(imported)
        project.close()
        project = None
        project = GhidraProject.openProject(str(project_parent), project_name, True)
        program = project.openProgram("/", program_name, False)
        if program is None:
            raise RuntimeError("Ghidra failed to reopen the saved fixture program")

        executable = AddressSet()
        for block in program.getMemory().getBlocks():
            if block.isExecute():
                executable.add(block.getStart(), block.getEnd())
        tx = program.startTransaction("Prepare fixture disassembly")
        committed = False
        try:
            command = DisassembleCommand(executable, executable, False)
            command.enableCodeAnalysis(False)
            if not command.applyTo(program):
                raise RuntimeError(f"Disassembly failed: {command.getStatusMsg()}")
            committed = True
        finally:
            program.endTransaction(tx, committed)

        enabled = configure_analysis(project, program)
        expected = sorted({ANALYZER, *DEPENDENCIES})
        if enabled != expected:
            raise RuntimeError(f"Unexpected enabled analysis options: {enabled}")
        project.analyze(program)
        output_path.write_text(report(input_path, enabled, table_facts(program)), encoding="utf-8", newline="\n")
        project.save(program)
        print(f"[+] Wrote {output_path}")
    finally:
        if project is not None:
            if "program" in locals():
                project.save(program)
            project.close()
        shutil.rmtree(project_parent, ignore_errors=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
