"""Generate the x86 constant-reference report through isolated PyGhidra analysis."""

from __future__ import annotations

import shutil
import sys
import tempfile
from pathlib import Path


ANALYZER_NAME = "x86 Constant Reference Analyzer"


def address_text(address) -> str:
    """Render an x86 PE address as a fixed-width offset."""
    return f"0x{int(address.getOffset()):08X}"


def executable_set(program):
    """Return executable ranges used as explicit, analysis-free disassembly seeds."""
    from ghidra.program.model.address import AddressSet

    addresses = AddressSet()
    for block in program.getMemory().getBlocks():
        if block.isExecute():
            addresses.add(block.getStart(), block.getEnd())
    return addresses


def prepare_disassembly(program) -> None:
    """Disassemble the x86 PE while leaving constant propagation isolated."""
    from ghidra.app.cmd.disassemble import DisassembleCommand

    transaction = program.startTransaction("Prepare x86 constant-reference disassembly")
    committed = False
    try:
        addresses = executable_set(program)
        command = DisassembleCommand(addresses, addresses, False)
        command.enableCodeAnalysis(False)
        if not command.applyTo(program):
            raise RuntimeError(f"Disassembly failed: {command.getStatusMsg()}")
        committed = True
    finally:
        program.endTransaction(transaction, committed)


def configure_analysis(project, program) -> list[str]:
    """Disable unrelated boolean analyzers and enable only X86Analyzer's option."""
    from ghidra.framework.options import OptionType

    options = project.getAnalysisOptions(program)
    for name in options.getOptionNames():
        if options.getType(name) == OptionType.BOOLEAN_TYPE:
            options.setBoolean(name, name == ANALYZER_NAME)
    enabled = [
        str(name)
        for name in options.getOptionNames()
        if options.getType(name) == OptionType.BOOLEAN_TYPE and options.getBoolean(name, False)
    ]
    if sorted(enabled) != [ANALYZER_NAME]:
        raise RuntimeError(f"Unexpected enabled analysis options: {sorted(enabled)}")
    return sorted(enabled)


def lea_rows(program):
    """Extract every LEA and its operand references before or after analysis."""
    rows = []
    instructions = program.getListing().getInstructions(program.getMemory().getExecuteSet(), True)
    while instructions.hasNext():
        instruction = instructions.next()
        if instruction.getMnemonicString() != "LEA":
            continue
        references = instruction.getOperandReferences(1)
        rows.append(
            (
                int(instruction.getAddress().getOffset()),
                tuple((int(reference.getToAddress().getOffset()), str(reference.getReferenceType())) for reference in references),
            )
        )
    return sorted(rows)


def keyed_delta(before, after):
    """Compare LEA reference snapshots by the stable instruction address."""
    before_by_key = {row[0]: row for row in before}
    after_by_key = {row[0]: row for row in after}
    added = [after_by_key[key] for key in sorted(set(after_by_key) - set(before_by_key))]
    removed = [before_by_key[key] for key in sorted(set(before_by_key) - set(after_by_key))]
    changed = [
        (before_by_key[key], after_by_key[key])
        for key in sorted(set(before_by_key) & set(after_by_key))
        if before_by_key[key] != after_by_key[key]
    ]
    return added, removed, changed


def row_text(row) -> str:
    """Render one LEA snapshot row safely inside a Markdown table cell."""
    return "; ".join(str(value) for value in row).replace("|", "\\|")


def append_delta(lines: list[str], title: str, before, after) -> None:
    """Append added, removed, and changed operand-reference rows."""
    added, removed, changed = keyed_delta(before, after)
    lines.extend([f"### {title}", "", "| Change | Before | After |", "| --- | --- | --- |"])
    if not added and not removed and not changed:
        lines.append("No changes observed")
        lines.append("")
        return
    for row in added:
        lines.append(f"| Added | - | `{row_text(row)}` |")
    for row in removed:
        lines.append(f"| Removed | `{row_text(row)}` | - |")
    for old, new in changed:
        lines.append(f"| Changed | `{row_text(old)}` | `{row_text(new)}` |")
    lines.append("")


def markdown(input_path: Path, pdb_path: Path, enabled: list[str], before, after) -> str:
    """Render explicit before/after LEA reference snapshots and their delta."""
    lines = [
        "# x86 Constant Reference Behavioral Fixture",
        "",
        "> Generated by PyGhidra from the checked-in MSVC x86 PE/PDB.",
        "> The only enabled boolean analyzer was `x86 Constant Reference Analyzer`.",
        "",
        "## Input",
        "",
        f"- **File:** `{input_path.name}`",
        f"- **File size:** `{input_path.stat().st_size}` bytes",
        f"- **Matching PDB:** `{pdb_path.name}` (CodeView identity verified before setup)",
        "",
        "## Analysis Configuration",
        "",
        *[f"- `{name}`" for name in enabled],
        "",
    ]
    for heading, rows in (("Before target analysis", before), ("After target analysis", after)):
        lines.extend([f"## {heading}", "", "### Target references", "", "| LEA address | Operand DATA references |", "| --- | --- |"])
        for address, references in rows:
            rendered = ", ".join(f"0x{target:08X} ({kind})" for target, kind in references) or "none"
            lines.append(f"| `0x{address:08X}` | `{rendered}` |")
        if not rows:
            lines.append("| - | No rows observed |")
        lines.append("")
    lines.extend(["## Delta", ""])
    append_delta(lines, "References", before, after)
    lines.extend(
        [
            "",
            "## Fixture Assertion",
            "",
            f"- **LEA instruction snapshots before/after:** `{len(before)}` / `{len(after)}`.",
            f"- **Operand references before/after:** `{sum(len(row[1]) for row in before)}` / `{sum(len(row[1]) for row in after)}`.",
            "- The added DATA reference is attributed to the target only because it is present after analysis and absent from the pre-target snapshot.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    """Import, reopen, isolate, analyze, save, and close the x86 project."""
    fixture_dir = Path(__file__).resolve().parent
    input_path = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else fixture_dir / "test_x86_constant_reference.exe"
    output_path = Path(sys.argv[2]).resolve() if len(sys.argv) > 2 else fixture_dir / "test_x86_constant_reference.md"
    if not input_path.is_file():
        print(f"Input file does not exist: {input_path}", file=sys.stderr)
        return 2
    pdb_path = input_path.with_suffix(".pdb")
    if not pdb_path.is_file():
        print(f"Matching PDB is required: {pdb_path}", file=sys.stderr)
        return 2

    import pyghidra

    pyghidra.start()
    from ghidra.base.project import GhidraProject
    from java.io import File
    sys.path.insert(0, str(fixture_dir.parent))
    from pdb_validation import validate_pdb_match

    parent = Path(tempfile.mkdtemp(prefix="ghidra_x86_constant_reference_"))
    project = None
    program = None
    try:
        project = GhidraProject.createProject(str(parent), "x86_constant_reference", True)
        imported = project.importProgram(File(str(input_path)))
        if imported is None:
            raise RuntimeError("Ghidra failed to import the x86 constant-reference fixture")
        project.saveAs(imported, "/", input_path.name, True)
        project.close(imported)
        program = project.openProgram("/", input_path.name, False)
        validate_pdb_match(program, pdb_path)
        prepare_disassembly(program)
        if str(program.getLanguage().getProcessor()) != "x86":
            raise RuntimeError(f"Expected x86 processor, got {program.getLanguage().getProcessor()}")
        before = lea_rows(program)
        enabled = configure_analysis(project, program)
        project.analyze(program)
        after = lea_rows(program)
        added, _, changed = keyed_delta(before, after)
        if not after or (not added and not changed):
            raise RuntimeError(f"x86 LEA reference was not created: before={before}, after={after}")
        output_path.write_text(markdown(input_path, pdb_path, enabled, before, after), encoding="utf-8", newline="\n")
        project.save(program)
    finally:
        if project is not None and program is not None:
            project.close(program)
        if project is not None:
            project.close()
        shutil.rmtree(parent, ignore_errors=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
