"""Generate the x86 constant-reference report through isolated PyGhidra analysis."""

from __future__ import annotations

import shutil
import sys
import tempfile
from pathlib import Path


ANALYZER_NAME = "x86 Constant Reference Analyzer"


def address_text(address) -> str:
    """Render an x86 PE address as a fixed-width offset."""
    return f"0x{int(address.getOffset()):08X}"


def executable_set(program):
    """Return executable ranges used as explicit, analysis-free disassembly seeds."""
    from ghidra.program.model.address import AddressSet

    addresses = AddressSet()
    for block in program.getMemory().getBlocks():
        if block.isExecute():
            addresses.add(block.getStart(), block.getEnd())
    return addresses


def prepare_disassembly(program) -> None:
    """Disassemble the x86 PE while leaving constant propagation isolated."""
    from ghidra.app.cmd.disassemble import DisassembleCommand

    transaction = program.startTransaction("Prepare x86 constant-reference disassembly")
    committed = False
    try:
        addresses = executable_set(program)
        command = DisassembleCommand(addresses, addresses, False)
        command.enableCodeAnalysis(False)
        if not command.applyTo(program):
            raise RuntimeError(f"Disassembly failed: {command.getStatusMsg()}")
        committed = True
    finally:
        program.endTransaction(transaction, committed)


def configure_analysis(project, program) -> list[str]:
    """Disable unrelated boolean analyzers and enable only X86Analyzer's option."""
    from ghidra.framework.options import OptionType

    options = project.getAnalysisOptions(program)
    for name in options.getOptionNames():
        if options.getType(name) == OptionType.BOOLEAN_TYPE:
            options.setBoolean(name, name == ANALYZER_NAME)
    enabled = [
        str(name)
        for name in options.getOptionNames()
        if options.getType(name) == OptionType.BOOLEAN_TYPE and options.getBoolean(name, False)
    ]
    if sorted(enabled) != [ANALYZER_NAME]:
        raise RuntimeError(f"Unexpected enabled analysis options: {sorted(enabled)}")
    return sorted(enabled)


def lea_rows(program):
    """Extract every LEA and its operand references before or after analysis."""
    rows = []
    instructions = program.getListing().getInstructions(program.getMemory().getExecuteSet(), True)
    while instructions.hasNext():
        instruction = instructions.next()
        if instruction.getMnemonicString() != "LEA":
            continue
        references = instruction.getOperandReferences(1)
        rows.append(
            (
                int(instruction.getAddress().getOffset()),
                tuple((int(reference.getToAddress().getOffset()), str(reference.getReferenceType())) for reference in references),
            )
        )
    return sorted(rows)


def markdown(input_path: Path, enabled: list[str], before, after) -> str:
    """Render actual x86 LEA reference evidence from the imported program."""
    lines = [
        "# x86 Constant Reference Behavioral Fixture",
        "",
        "> Generated by PyGhidra from the checked-in MSVC x86 PE/PDB.",
        "> The only enabled boolean analyzer was `x86 Constant Reference Analyzer`.",
        "",
        "## Input",
        "",
        f"- **File:** `{input_path.name}`",
        f"- **File size:** `{input_path.stat().st_size}` bytes",
        "",
        "## Analysis Configuration",
        "",
        *[f"- `{name}`" for name in enabled],
        "",
        "## LEA Operand References",
        "",
        "| Phase | LEA address | Operand DATA references |",
        "| --- | --- | --- |",
    ]
    for phase, rows in (("Before", before), ("After", after)):
        for address, references in rows:
            rendered = ", ".join(f"0x{target:08X} ({kind})" for target, kind in references) or "none"
            lines.append(f"| {phase} | `0x{address:08X}` | `{rendered}` |")
    lines.extend(
        [
            "",
            "## Fixture Assertion",
            "",
            f"- **LEA instructions:** `{len(after)}`.",
            f"- **New operand references:** `{sum(len(row[1]) for row in after) - sum(len(row[1]) for row in before)}`.",
            "- The post-analysis LEA references the initialized `target_value` memory address with an analysis DATA reference.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    """Import, reopen, isolate, analyze, save, and close the x86 project."""
    fixture_dir = Path(__file__).resolve().parent
    input_path = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else fixture_dir / "test_x86_constant_reference.exe"
    output_path = Path(sys.argv[2]).resolve() if len(sys.argv) > 2 else fixture_dir / "test_x86_constant_reference.md"
    if not input_path.is_file():
        print(f"Input file does not exist: {input_path}", file=sys.stderr)
        return 2

    import pyghidra

    pyghidra.start()
    from ghidra.base.project import GhidraProject
    from java.io import File

    parent = Path(tempfile.mkdtemp(prefix="ghidra_x86_constant_reference_"))
    project = None
    program = None
    try:
        project = GhidraProject.createProject(str(parent), "x86_constant_reference", True)
        imported = project.importProgram(File(str(input_path)))
        if imported is None:
            raise RuntimeError("Ghidra failed to import the x86 constant-reference fixture")
        project.saveAs(imported, "/", input_path.name, True)
        project.close(imported)
        program = project.openProgram("/", input_path.name, False)
        prepare_disassembly(program)
        if str(program.getLanguage().getProcessor()) != "x86":
            raise RuntimeError(f"Expected x86 processor, got {program.getLanguage().getProcessor()}")
        before = lea_rows(program)
        enabled = configure_analysis(project, program)
        project.analyze(program)
        after = lea_rows(program)
        new_references = sum(len(row[1]) for row in after) - sum(len(row[1]) for row in before)
        if not after or new_references < 1:
            raise RuntimeError(f"x86 LEA reference was not created: before={before}, after={after}")
        output_path.write_text(markdown(input_path, enabled, before, after), encoding="utf-8", newline="\n")
        project.save(program)
    finally:
        if project is not None and program is not None:
            project.close(program)
        if project is not None:
            project.close()
        shutil.rmtree(parent, ignore_errors=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
