add_library(analyzer_x86_constant_reference STATIC)
target_sources(analyzer_x86_constant_reference PUBLIC FILE_SET cxx_modules TYPE CXX_MODULES FILES src/x86_constant_reference.cppm)
target_link_libraries(analyzer_x86_constant_reference PUBLIC ReCode::AnalyzerShared)
target_compile_features(analyzer_x86_constant_reference PUBLIC cxx_std_23)

if(BUILD_TESTING)
    find_package(GTest CONFIG REQUIRED)
    add_executable(analyzer_x86_constant_reference_tests)
    target_sources(analyzer_x86_constant_reference_tests PRIVATE FILE_SET cxx_modules TYPE CXX_MODULES FILES tests/x86_constant_reference_tests.cppm)
    target_link_libraries(analyzer_x86_constant_reference_tests PRIVATE analyzer_x86_constant_reference ReCode::AnalyzerTestSupport GTest::gtest_main)
    target_compile_features(analyzer_x86_constant_reference_tests PRIVATE cxx_std_23)
    add_test(NAME analyzer_x86_constant_reference_tests COMMAND analyzer_x86_constant_reference_tests)
endif()
