"""Generate the Windows resource-reference report through isolated PyGhidra analysis."""

from __future__ import annotations

import re
import shutil
import sys
import tempfile
from pathlib import Path


ANALYZER_NAME = "WindowsResourceReference"


def address_text(address) -> str:
    """Render a Ghidra address as a fixed-width PE offset."""
    return f"0x{int(address.getOffset()):016X}"


def executable_set(program):
    """Return executable memory ranges for the explicit disassembly prerequisite."""
    from ghidra.program.model.address import AddressSet

    addresses = AddressSet()
    for block in program.getMemory().getBlocks():
        if block.isExecute():
            addresses.add(block.getStart(), block.getEnd())
    return addresses


def prepare_disassembly(program) -> None:
    """Disassemble PE code without allowing unrelated analyzers to run first."""
    from ghidra.app.cmd.disassemble import DisassembleCommand

    transaction = program.startTransaction("Prepare Windows resource disassembly")
    committed = False
    try:
        addresses = executable_set(program)
        command = DisassembleCommand(addresses, addresses, False)
        command.enableCodeAnalysis(False)
        if not command.applyTo(program):
            raise RuntimeError(f"Disassembly failed: {command.getStatusMsg()}")
        committed = True
    finally:
        program.endTransaction(transaction, committed)


def configure_analysis(project, program) -> list[str]:
    """Disable every boolean analyzer and enable only WindowsResourceReference."""
    from ghidra.framework.options import OptionType

    options = project.getAnalysisOptions(program)
    for name in options.getOptionNames():
        if options.getType(name) == OptionType.BOOLEAN_TYPE:
            options.setBoolean(name, name == ANALYZER_NAME)
    enabled = [
        str(name)
        for name in options.getOptionNames()
        if options.getType(name) == OptionType.BOOLEAN_TYPE and options.getBoolean(name, False)
    ]
    if sorted(enabled) != [ANALYZER_NAME]:
        raise RuntimeError(f"Unexpected enabled analysis options: {sorted(enabled)}")
    return sorted(enabled)


def resource_symbols(program):
    """Extract PE-loader resource symbols, type prefixes, IDs, and addresses."""
    rows = []
    for symbol in program.getSymbolTable().getAllSymbols(True):
        name = str(symbol.getName())
        if not name.startswith("Rsrc_"):
            continue
        resource_type = name.split("_", 2)[1] if "_" in name else name
        identifiers = re.findall(r"_[0-9A-Fa-f]+", name)
        identifier = identifiers[-1][1:] if identifiers else "table"
        rows.append((resource_type, identifier, int(symbol.getAddress().getOffset()), name))
    return sorted(rows, key=lambda row: (row[0], row[2], row[3]))


def resource_references(program):
    """Extract DATA mnemonic references created by WindowsResourceReference.java."""
    from ghidra.program.model.symbol import RefType

    rows = []
    instructions = program.getListing().getInstructions(program.getMemory().getExecuteSet(), True)
    while instructions.hasNext():
        instruction = instructions.next()
        for reference in instruction.getMnemonicReferences():
            if reference.getReferenceType() != RefType.DATA:
                continue
            target = program.getSymbolTable().getPrimarySymbol(reference.getToAddress())
            rows.append((int(instruction.getAddress().getOffset()), int(reference.getToAddress().getOffset()), str(target.getName()) if target else "unnamed"))
    return sorted(set(rows))


def markdown(input_path: Path, enabled: list[str], symbols, references) -> str:
    """Render actual resource types/IDs/addresses and analyzer-created DATA references."""
    lines = [
        "# Windows Resource Reference Behavioral Fixture",
        "",
        "> Generated by PyGhidra from the MSVC x64 PE linked with `rc.exe` output.",
        "> The only enabled boolean analyzer was `WindowsResourceReference`.",
        "",
        "## Input",
        "",
        f"- **File:** `{input_path.name}`",
        f"- **File size:** `{input_path.stat().st_size}` bytes",
        "",
        "## Analysis Configuration",
        "",
        *[f"- `{name}`" for name in enabled],
        "",
        "## PE Resource Symbols",
        "",
        "| Resource type | ID/table | Address | Loader symbol |",
        "| --- | --- | --- | --- |",
    ]
    for resource_type, identifier, address, name in symbols:
        lines.append(f"| `{resource_type}` | `{identifier}` | `0x{address:016X}` | `{name}` |")
    lines.extend(["", "## Analyzer DATA References", "", "| Instruction | Resource address | Resource symbol |", "| --- | --- | --- |"])
    for instruction, target, name in references:
        lines.append(f"| `0x{instruction:016X}` | `0x{target:016X}` | `{name}` |")
    lines.extend(
        [
            "",
            "## Fixture Assertion",
            "",
            f"- **Resource symbols reported:** `{len(symbols)}`.",
            f"- **Analyzer DATA references reported:** `{len(references)}`.",
            "- The resource section contains STRINGTABLE, DIALOGEX, and MENU entries; the two LoadStringW calls must resolve to string-table data addresses.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    """Import, reopen, isolate, analyze, save, and close the resource project."""
    fixture_dir = Path(__file__).resolve().parent
    input_path = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else fixture_dir / "test_windows_resource_reference.exe"
    output_path = Path(sys.argv[2]).resolve() if len(sys.argv) > 2 else fixture_dir / "test_windows_resource_reference.md"
    if not input_path.is_file():
        print(f"Input file does not exist: {input_path}", file=sys.stderr)
        return 2

    import pyghidra

    pyghidra.start()
    from ghidra.base.project import GhidraProject
    from java.io import File

    parent = Path(tempfile.mkdtemp(prefix="ghidra_windows_resource_reference_"))
    project = None
    program = None
    script_host_acquired = False
    try:
        # WindowsResourceReferenceAnalyzer.java delegates to a module GhidraScript;
        # standalone PyGhidra has to initialize the script bundle registry explicitly.
        from ghidra.app.script import GhidraScriptUtil

        GhidraScriptUtil.acquireBundleHostReference()
        script_host_acquired = True
        project = GhidraProject.createProject(str(parent), "windows_resource_reference", True)
        imported = project.importProgram(File(str(input_path)))
        if imported is None:
            raise RuntimeError("Ghidra failed to import the resource fixture")
        project.saveAs(imported, "/", input_path.name, True)
        project.close(imported)
        program = project.openProgram("/", input_path.name, False)
        prepare_disassembly(program)
        enabled = configure_analysis(project, program)
        project.analyze(program)
        symbols = resource_symbols(program)
        references = resource_references(program)
        if not symbols or not references:
            raise RuntimeError(f"Expected loader resource symbols and DATA references, got {len(symbols)} and {len(references)}")
        output_path.write_text(markdown(input_path, enabled, symbols, references), encoding="utf-8", newline="\n")
        project.save(program)
    finally:
        if project is not None and program is not None:
            project.close(program)
        if project is not None:
            project.close()
        if script_host_acquired:
            GhidraScriptUtil.releaseBundleHostReference()
        shutil.rmtree(parent, ignore_errors=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
