add_library(analyzer_demangler_microsoft STATIC)
target_sources(analyzer_demangler_microsoft PUBLIC FILE_SET cxx_modules TYPE CXX_MODULES FILES src/demangler_microsoft.cppm)
target_link_libraries(analyzer_demangler_microsoft PUBLIC ReCode::AnalyzerShared)
target_compile_features(analyzer_demangler_microsoft PUBLIC cxx_std_23)

if(BUILD_TESTING)
    find_package(GTest CONFIG REQUIRED)
    add_executable(analyzer_demangler_microsoft_tests)
    target_sources(analyzer_demangler_microsoft_tests PRIVATE FILE_SET cxx_modules TYPE CXX_MODULES FILES tests/demangler_microsoft_tests.cppm)
    target_link_libraries(analyzer_demangler_microsoft_tests PRIVATE analyzer_demangler_microsoft ReCode::AnalyzerTestSupport GTest::gtest_main)
    target_compile_features(analyzer_demangler_microsoft_tests PRIVATE cxx_std_23)
    add_test(NAME analyzer_demangler_microsoft_tests COMMAND analyzer_demangler_microsoft_tests)
endif()
