#!/usr/bin/env python3
"""Run Decompiler Switch Analysis and extract recovered switch labels/references."""

from __future__ import annotations

import shutil
import sys
import tempfile
from pathlib import Path


ANALYZER = "Decompiler Switch Analysis"
DEPENDENCIES: tuple[str, ...] = ()


def address_text(address) -> str:
    """Render a Ghidra address as a stable offset."""
    return f"0x{int(address.getOffset()):016X}"


def configure_analysis(project, program) -> list[str]:
    """Disable unrelated boolean analyzers and enable switch analysis explicitly."""
    from ghidra.framework.options import OptionType

    options = project.getAnalysisOptions(program)
    enabled_names = {ANALYZER, *DEPENDENCIES}
    for name in options.getOptionNames():
        if options.getType(name) == OptionType.BOOLEAN_TYPE:
            options.setBoolean(name, str(name) in enabled_names)
    return sorted(str(name) for name in options.getOptionNames()
                  if options.getType(name) == OptionType.BOOLEAN_TYPE and options.getBoolean(name, False))


def prepare_code(program) -> None:
    """Disassemble executable bytes and create function objects for exported code symbols."""
    from ghidra.app.cmd.disassemble import DisassembleCommand
    from ghidra.app.cmd.function import CreateFunctionCmd
    from ghidra.program.model.address import AddressSet
    from ghidra.program.model.symbol import SymbolType

    executable = AddressSet()
    for block in program.getMemory().getBlocks():
        if block.isExecute():
            executable.add(block.getStart(), block.getEnd())
    tx = program.startTransaction("Prepare fixture functions")
    committed = False
    try:
        command = DisassembleCommand(executable, executable, False)
        command.enableCodeAnalysis(False)
        if not command.applyTo(program):
            raise RuntimeError(f"Disassembly failed: {command.getStatusMsg()}")
        for symbol in program.getSymbolTable().getAllSymbols(True):
            address = symbol.getAddress()
            if symbol.getSymbolType() == SymbolType.FUNCTION and executable.contains(address):
                if program.getFunctionManager().getFunctionAt(address) is None:
                    CreateFunctionCmd(address).applyTo(program)
        committed = True
    finally:
        program.endTransaction(tx, committed)


def switch_facts(program):
    """Extract switchD symbols and computed-jump references without decompiler text."""
    symbols = []
    for symbol in program.getSymbolTable().getAllSymbols(True):
        if symbol.getName().startswith("switchD"):
            symbols.append((address_text(symbol.getAddress()), symbol.getName()))
    computed = []
    for instruction in program.getListing().getInstructions(program.getMemory().getExecuteSet(), True):
        if instruction.getFlowType().isJump() and instruction.getFlowType().isComputed():
            targets = sorted(address_text(ref.getToAddress()) for ref in instruction.getReferencesFrom())
            computed.append((address_text(instruction.getAddress()), targets))
    return sorted(symbols), sorted(computed)


def report(input_path: Path, enabled: list[str], facts) -> str:
    """Render stable labels and computed case-reference facts."""
    labels, computed = facts
    lines = ["# Decompiler Switch Analysis Behavioral Fixture", "",
             "> Generated by PyGhidra; only stable switch labels and references are extracted.", "",
             "## Analysis Configuration", "", f"- **Input:** `{input_path.name}`",
             f"- **Enabled boolean analyzers:** `{', '.join(enabled)}`", "", "## Switch Labels", "",
             "| Address | Symbol |", "| --- | --- |"]
    lines.extend(f"| `{address}` | `{name}` |" for address, name in labels)
    lines.extend(["", "## Computed Jump References", "", "| Dispatch | Case references |", "| --- | --- |"])
    lines.extend(f"| `{address}` | `{', '.join(targets)}` |" for address, targets in computed)
    lines.extend(["", "## Fixture Assertions", "", f"- **Recovered switch labels:** `{len(labels)}`", ""])
    return "\n".join(lines)


def main() -> int:
    """Create, save, reopen, analyze, save, and close an isolated Ghidra project."""
    fixture_dir = Path(__file__).resolve().parent
    input_path = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else fixture_dir / "test_decompiler_switch_analysis.exe"
    output_path = Path(sys.argv[2]).resolve() if len(sys.argv) > 2 else fixture_dir / "test_decompiler_switch_analysis.md"
    if not input_path.is_file():
        print(f"Input file does not exist: {input_path}", file=sys.stderr)
        return 2
    import pyghidra

    pyghidra.start()
    from ghidra.base.project import GhidraProject
    from java.io import File

    project_parent = Path(tempfile.mkdtemp(prefix="ghidra_decompiler_switch_analysis_"))
    project = None
    try:
        project = GhidraProject.createProject(str(project_parent), "decompiler_switch_analysis", False)
        imported = project.importProgram(File(str(input_path)))
        if imported is None:
            raise RuntimeError("Ghidra failed to import the fixture executable")
        project.saveAs(imported, "/", input_path.name, True)
        project.save(imported)
        project.close()
        project = None
        project = GhidraProject.openProject(str(project_parent), "decompiler_switch_analysis", True)
        program = project.openProgram("/", input_path.name, False)
        if program is None:
            raise RuntimeError("Ghidra failed to reopen the saved fixture program")
        prepare_code(program)
        enabled = configure_analysis(project, program)
        if enabled != [ANALYZER]:
            raise RuntimeError(f"Unexpected enabled analysis options: {enabled}")
        project.analyze(program)
        output_path.write_text(report(input_path, enabled, switch_facts(program)), encoding="utf-8", newline="\n")
        project.save(program)
        print(f"[+] Wrote {output_path}")
    finally:
        if project is not None:
            if "program" in locals():
                project.save(program)
            project.close()
        shutil.rmtree(project_parent, ignore_errors=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
